LOCK TABLES `setting_type` WRITE;
/*!40000 ALTER TABLE `setting_type` DISABLE KEYS */;
INSERT INTO `setting_type` VALUES
(1,'DomainEntity.Detail.Display.GalleryViewableDocuments','Display viewable documents in the gallery.','true'),
(1000,'AllowedPropertyValue.List.Display.Description','Display allowed property value description.','false'),
(1001,'AllowedPropertyValue.List.Display.Id','Display allowed property value id.','false'),
(1002,'AllowedPropertyValue.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(1003,'AllowedPropertyValue.List.Display.SortOrder','Display allowed property value sort order.','true'),
(1004,'AllowedPropertyValue.List.Display.Units','Display allowed property value units.','true'),
(1005,'AllowedPropertyValue.List.FilterBy.Description','Filter for allowed property value description.',NULL),
(1006,'AllowedPropertyValue.List.FilterBy.SortOrder','Filter for allowed property value class sort order.',NULL),
(1007,'AllowedPropertyValue.List.FilterBy.Units','Filter for allowed property value units.',NULL),
(1008,'AllowedPropertyValue.List.FilterBy.Value','Filter for allowed property value.',NULL),
(2000,'ItemDomainCatalog.List.AutoLoad.FilterBy.Properties','Automatically load component list with display properties for filtering.','true'),
(2001,'ItemDomainCatalog.List.Display.Category','Display catalog item category.','true'),
(2002,'ItemDomainCatalog.List.Display.CreatedByUser','Display created by username.','false'),
(2003,'ItemDomainCatalog.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(2004,'ItemDomainCatalog.List.Display.Description','Display component description.','true'),
(2005,'ItemDomainCatalog.List.Display.Id','Display component id.','false'),
(2006,'ItemDomainCatalog.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(2007,'ItemDomainCatalog.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(2008,'ItemDomainCatalog.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(2009,'ItemDomainCatalog.List.Display.ModelNumber','Display component model number.','true'),
(2010,'ItemDomainCatalog.List.Display.OwnerUser','Display owner username.','false'),
(2011,'ItemDomainCatalog.List.Display.OwnerGroup','Display owner group name.','false'),
(2012,'ItemDomainCatalog.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(2013,'ItemDomainCatalog.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(2014,'ItemDomainCatalog.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(2015,'ItemDomainCatalog.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(2016,'ItemDomainCatalog.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(2017,'ItemDomainCatalog.List.Display.Sources','Display component sources.','false'),
(2018,'ItemDomainCatalog.List.Display.Type','Display component type.','true'),
(2019,'ItemDomainCatalog.List.Display.RowExpansion','Display row expansion.','true'),
(2020,'ItemDomainCatalog.List.Display.ComponentInstance.RowExpansion','Display Component Instance row expansion.','true'),
(2021,'ItemDomainCatalog.List.Display.AlternateName','Display Alternate Name','false'),
(2022,'ItemDomainCatalog.List.Display.Project','Display Item Project','false'),
(2023,'ItemDomainCatalog.List.Display.EntityTypes','Display Item Entity Types','true'),
(2024,'ItemDomainCatalog.List.Load.RowExpansionPropertyValue','Load property values for row expansions.','false'),
(2025,'ItemDomainCatalog.List.Load.ComponentInstance.RowExpansionPropertyValue','Load property values for component instance row expansions.','false'),
(2026,'ItemDomainCatalog.List.FilterBy.Category','Filter for components by type category.',NULL),
(2027,'ItemDomainCatalog.List.FilterBy.CreatedByUser','Filter for components that were created by username.',NULL),
(2028,'ItemDomainCatalog.List.FilterBy.CreatedOnDateTime','Filter for components that were created on date/time.',NULL),
(2029,'ItemDomainCatalog.List.FilterBy.Description','Filter for components by description.',NULL),
(2030,'ItemDomainCatalog.List.FilterBy.LastModifiedByUser','Filter for components that were last modified by username.',NULL),
(2031,'ItemDomainCatalog.List.FilterBy.LastModifiedOnDateTime','Filter for components that were last modified on date/time.',NULL),
(2032,'ItemDomainCatalog.List.FilterBy.ModelNumber','Filter for component model number.',NULL),
(2033,'ItemDomainCatalog.List.FilterBy.PropertyValue1','Filter for property value with displayed property type id #1.',''),
(2034,'ItemDomainCatalog.List.FilterBy.PropertyValue2','Filter for property value with displayed property type id #2.',''),
(2035,'ItemDomainCatalog.List.FilterBy.PropertyValue3','Filter for property value with displayed property type id #3.',''),
(2036,'ItemDomainCatalog.List.FilterBy.PropertyValue4','Filter for property value with displayed property type id #4.',''),
(2037,'ItemDomainCatalog.List.FilterBy.PropertyValue5','Filter for property value with displayed property type id #5.',''),
(2038,'ItemDomainCatalog.List.FilterBy.Name','Filter for components by name.',NULL),
(2039,'ItemDomainCatalog.List.FilterBy.OwnerUser','Filter for components by owner username.',NULL),
(2040,'ItemDomainCatalog.List.FilterBy.OwnerGroup','Filter for components by owner group name.',NULL),
(2041,'ItemDomainCatalog.List.FilterBy.Sources','Filter for components by sources.',NULL),
(2042,'ItemDomainCatalog.List.FilterBy.Type','Filter for components by type.',NULL),
(2043,'ItemDomainCatalog.Help.ListPage.Display.Fragment','Display Help guide to the user on the main list page of the Component entity.','true'),
(2044,'ItemDomainCatalog.List.Scope.Display','Show list page with a scope applied.','All'),
(2045,'ItemDomainCatalog.List.Scope.Display.PropertyTypeId','Setting used along side a display scope of property type.',NULL),
(2046,'ItemDomainCatalog.ItemElementList.Display.ItemIdentifier1','Display column for item identifier 1 in the item elements list.','true'),
(2047,'ItemDomainCatalog.List.Load.FilterDataTable','Automatically load list filter values in data table on page load.','true'),
(2048,'ItemDomainCatalog.ItemElementList.Display.ItemIdentifier2','Display column for item identifier 2 in the item elements list.','false'),
(2049,'ItemDomainCatalog.ItemElementList.Display.ItemType','Display column for item type in the item elements list.','false'),
(2050,'ItemDomainCatalog.ItemElementList.Display.ItemCategory','Display column for item category in the item elements list.','false'),
(2051,'ItemDomainCatalog.ItemElementList.Display.Source','Display column for source in the item elements list.','false'),
(2052,'ItemDomainCatalog.ItemElementList.Display.Project','Display column for project in the item elements list.','false'),
(2053,'ItemDomainCatalog.ItemElementList.Display.Description','Display column for description in the item elements list.','false'),
(3000,'ItemDomainInventory.List.AutoLoad.FilterBy.Properties','Automatically load component instance list with display properties for filtering.','true'),
(3001,'ItemDomainInventory.List.Display.CreatedByUser','Display created by username.','false'),
(3002,'ItemDomainInventory.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(3003,'ItemDomainInventory.List.Display.Description','Display component instance description.','true'),
(3004,'ItemDomainInventory.List.Display.Id','Display component instance id.','false'),
(3005,'ItemDomainInventory.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(3006,'ItemDomainInventory.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(3007,'ItemDomainInventory.List.Display.Location','Display inventory item location.','true'),
(3008,'ItemDomainInventory.List.Display.LocationDetails','Display component instance location details.','false'),
(3009,'ItemDomainInventory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(3010,'ItemDomainInventory.List.Display.OwnerUser','Display owner username.','false'),
(3011,'ItemDomainInventory.List.Display.OwnerGroup','Display owner group name.','false'),
(3012,'ItemDomainInventory.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(3013,'ItemDomainInventory.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(3014,'ItemDomainInventory.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(3015,'ItemDomainInventory.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(3016,'ItemDomainInventory.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(3017,'ItemDomainInventory.List.Display.QrId','Display component instance QR id.','true'),
(3018,'ItemDomainInventory.List.Display.SerialNumber','Display component instance serial number.','true'),
(3019,'ItemDomainInventory.List.Display.Project','Display Inventory Item project.','false'),
(3020,'ItemDomainInventory.List.Display.EntityTypes','Display Inventory Item Entity Type.','true'),
(3021,'ItemDomainInventory.List.Display.RowExpansion','Display row expansion.','true'),
(3022,'ItemDomainInventory.List.Load.RowExpansionPropertyValue','Load property values for row expansions.','false'),
(3023,'ItemDomainInventory.List.FilterBy.Component','Filter for component instance component.',NULL),
(3024,'ItemDomainInventory.List.FilterBy.CreatedByUser','Filter for components that were created by username.',NULL),
(3025,'ItemDomainInventory.List.FilterBy.CreatedOnDateTime','Filter for components that were created on date/time.',NULL),
(3026,'ItemDomainInventory.List.FilterBy.Description','Filter for components by description.',NULL),
(3027,'ItemDomainInventory.List.FilterBy.LastModifiedByUser','Filter for components that were last modified by username.',NULL),
(3028,'ItemDomainInventory.List.FilterBy.LastModifiedOnDateTime','Filter for components that were last modified on date/time.',NULL),
(3029,'ItemDomainInventory.List.FilterBy.Location','Filter for component instance location.',NULL),
(3030,'ItemDomainInventory.List.FilterBy.LocationDetails','Filter for component instance location details.',NULL),
(3031,'ItemDomainInventory.List.FilterBy.OwnerUser','Filter for component instances by owner username.',NULL),
(3032,'ItemDomainInventory.List.FilterBy.OwnerGroup','Filter for component instances by owner group name.',NULL),
(3033,'ItemDomainInventory.List.FilterBy.PropertyValue1','Filter for property value with displayed property type id #1.',''),
(3034,'ItemDomainInventory.List.FilterBy.PropertyValue2','Filter for property value with displayed property type id #2.',''),
(3035,'ItemDomainInventory.List.FilterBy.PropertyValue3','Filter for property value with displayed property type id #3.',''),
(3036,'ItemDomainInventory.List.FilterBy.PropertyValue4','Filter for property value with displayed property type id #4.',''),
(3037,'ItemDomainInventory.List.FilterBy.PropertyValue5','Filter for property value with displayed property type id #5.',''),
(3038,'ItemDomainInventory.List.FilterBy.QrId','Filter for component instance QR id.',NULL),
(3039,'ItemDomainInventory.List.FilterBy.SerialNumber','Filter for component instance serial number.',NULL),
(3040,'ItemDomainInventory.List.FilterBy.Tag','Filter for component instance tag.',NULL),
(3041,'ItemDomainInventory.Help.ListPage.Display.Fragment','Display Help guide to the user on the main list page of the Component Instance entity.','true'),
(3042,'ItemDomainInventory.List.Scope.Display','Show list page with a scope applied.','All'),
(3043,'ItemDomainInventory.List.Scope.Display.PropertyTypeId','Setting used along side a display scope of property type.',NULL),
(3044,'ItemDomainInventory.ItemElementList.Display.ItemIdentifier1','Display column for item identifier 1 in the item elements list.','true'),
(3045,'ItemDomainInventory.List.Load.FilterDataTable','Automatically load list filter values in data table on page load.','true'),
(3046,'ItemDomainInventory.ItemElementList.Display.Project','Display column for project in the item elements list.','false'),
(3047,'ItemDomainInventory.ItemElementList.Display.Description','Display column for description in the item elements list.','false'),
(3048,'ItemDomainInventory.ItemElementList.Display.QrId','Display column for qrid in the item elements list.','false'),
(3049,'ItemDomainInventory.List.Display.Domain','Display column for domain in the item list.','false'),
(3050,'ItemDomainInventory.List.FilterBy.Domain','Filter for domain in the item list.',''),
(3051,'ItemDomainInventory.List.FilterBy.Status','Filter for components by status.',NULL),
(3052,'ItemDomainInventory.List.Display.Status','Display column for status in inventory list.','true'),
(4000,'ItemSource.List.Display.ContactInfo','Display component source contact info.','false'),
(4001,'ItemSource.List.Display.Cost','Display component cost.','true'),
(4002,'ItemSource.List.Display.Description','Display component source description.','true'),
(4003,'ItemSource.List.Display.Id','Display component source id.','false'),
(4004,'ItemSource.List.Display.IsManufacturer','Display component source manufacturer designation.','true'),
(4005,'ItemSource.List.Display.IsVendor','Display component source vendor designation.','true'),
(4006,'ItemSource.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(4007,'ItemSource.List.Display.PartNumber','Display component part number.','true'),
(4008,'ItemSource.List.Display.Url','Display component source URL.','false'),
(4009,'ItemSource.List.FilterBy.ContactInfo','Filter for component sources by contact info.',NULL),
(4010,'ItemSource.List.FilterBy.Cost','Filter for component sources by cost.',NULL),
(4011,'ItemSource.List.FilterBy.Description','Filter for component sources by description.',NULL),
(4012,'ItemSource.List.FilterBy.IsManufacturer','Filter for component sources by manufacturer designation.',NULL),
(4013,'ItemSource.List.FilterBy.IsVendor','Filter for component sources by vendor designation.',NULL),
(4014,'ItemSource.List.FilterBy.PartNumber','Filter for component sources by part number.',NULL),
(4015,'ItemSource.List.FilterBy.SourceName','Filter for component sources by name.',NULL),
(4016,'ItemSource.List.FilterBy.Url','Filter for component sources by URL.',NULL),
(5000,'ItemType.List.Display.Description','Display component type description.','true'),
(5001,'ItemType.List.Display.Id','Display component type id.','false'),
(5002,'ItemType.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(5003,'ItemType.List.FilterBy.Description','Filter for component type description.',NULL),
(5004,'ItemType.List.FilterBy.Name','Filter for component type name.',NULL),
(6000,'ItemCategory.List.Display.Description','Display item category description.','true'),
(6001,'ItemCategory.List.Display.Id','Display item category id.','false'),
(6002,'ItemCategory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(6003,'ItemCategory.List.FilterBy.Description','Filter for item category description.',NULL),
(6004,'ItemCategory.List.FilterBy.Name','Filter for item category name.',NULL),
(7000,'Item.Member.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(7001,'Item.Member.List.Display.Id','Display design id.','false'),
(7002,'Item.Member.List.Display.Description','Display design description.','true'),
(7003,'Item.Member.List.Display.OwnerUser','Display owner username.','true'),
(7004,'Item.Member.List.Display.OwnerGroup','Display owner group name.','true'),
(7005,'Item.Member.List.Display.CreatedByUser','Display created by username.','false'),
(7006,'Item.Member.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(7007,'Item.Member.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(7008,'Item.Member.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(8000,'ItemElement.List.Display.ChildDesign','Display child design.','false'),
(8001,'ItemElement.List.Display.Component','Display component.','false'),
(8002,'ItemElement.List.Display.ComponentType','Display component type.','false'),
(8003,'ItemElement.List.Display.CreatedByUser','Display created by username.','false'),
(8004,'ItemElement.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(8005,'ItemElement.List.Display.Description','Display design element description.','false'),
(8006,'ItemElement.List.Display.FlatTableView','Display flat table view for design element list.','true'),
(8007,'ItemElement.List.Display.Id','Display design element id.','false'),
(8008,'ItemElement.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(8009,'ItemElement.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(8010,'ItemElement.List.Display.Location','Display location.','false'),
(8011,'ItemElement.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(8012,'ItemElement.List.Display.OwnerUser','Display owner username.','true'),
(8013,'ItemElement.List.Display.OwnerGroup','Display owner group name.','true'),
(8014,'ItemElement.List.Display.SortOrder','Display design element sort order.','false'),
(8015,'ItemElement.List.Display.RowColor','Display design element row color.','true'),
(8016,'ItemElement.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(8017,'ItemElement.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(8018,'ItemElement.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(8019,'ItemElement.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(8020,'ItemElement.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(8021,'ItemElement.List.Display.RowExpansion','Display row expansion.','true'),
(8022,'ItemElement.List.Load.RowExpansionPropertyValue','Load property values for row expansions.','true'),
(8023,'ItemElement.List.Display.BillOfMaterialsActionColumn','Display design element list action column in the child design bill of materials.','false'),
(8024,'ItemElement.List.SortBy.PropertyTypeId','Allow user to sort using property type id or the default sort order(NULL)',NULL),
(8025,'ItemElement.List.FilterBy.ChildDesign','Filter for child design.',NULL),
(8026,'ItemElement.List.FilterBy.Component','Filter for component.',NULL),
(8027,'ItemElement.List.FilterBy.ComponentType','Filter for component type.',NULL),
(8028,'ItemElement.List.FilterBy.CreatedByUser','Filter for design elements that were created by username.',NULL),
(8029,'ItemElement.List.FilterBy.CreatedOnDateTime','Filter for design elements that were created on date/time.',NULL),
(8030,'ItemElement.List.FilterBy.Description','Filter for design elements by description.',NULL),
(8031,'ItemElement.List.FilterBy.LastModifiedByUser','Filter for design elements that were last modified by username.',NULL),
(8032,'ItemElement.List.FilterBy.LastModifiedOnDateTime','Filter for design elements that were last modified on date/time.',NULL),
(8033,'ItemElement.List.FilterBy.Location','Filter for component.',NULL),
(8034,'ItemElement.List.FilterBy.Name','Filter for design elements by name.',NULL),
(8035,'ItemElement.List.FilterBy.OwnerUser','Filter for design elements by owner username.',NULL),
(8036,'ItemElement.List.FilterBy.OwnerGroup','Filter for design elements by owner group name.',NULL),
(8037,'ItemElement.List.FilterBy.SortOrder','Filter for design elements by sort order.',NULL),
(8038,'ItemElement.List.Display.SimpleViewPartName','Display part name (element name) on the simple view.','true'),
(8039,'ItemElement.List.Display.SimpleViewPartDescription','Display part description (element description) on the simple view.','true'),
(9000,'Log.List.Display.Attachments','Display log entry attachments.','true'),
(9001,'Log.List.Display.EnteredOnDateTime','Display log entry entered on date/time.','false'),
(9002,'Log.List.Display.EnteredByUser','Display log entry entered by user.','true'),
(9003,'Log.List.Display.Id','Display log entry id.','false'),
(9004,'Log.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(9005,'Log.List.Display.Topic','Display log topic.','false'),
(9006,'Log.List.FilterBy.EnteredOnDateTime','Filter for log entry entered on date/time.',NULL),
(9007,'Log.List.FilterBy.EnteredByUser','Filter for log entry entered by user.',NULL),
(9008,'Log.List.FilterBy.Text','Filter for log entry text.',NULL),
(9009,'Log.List.FilterBy.Topic','Filter for log topic.',NULL),
(9010,'Log.List.Display.EffectiveFromDateTime','Display effective from date/time', 'true'),
(9011,'Log.List.Display.EffectiveToDateTime','Display effective to date/time', 'false'), 
(10000,'PropertyType.List.Display.Category','Display property type category.','true'),
(10001,'PropertyType.List.Display.DefaultUnits','Display property type default units.','false'),
(10002,'PropertyType.List.Display.DefaultValue','Display property type default value.','false'),
(10003,'PropertyType.List.Display.Description','Display property type description.','true'),
(10004,'PropertyType.List.Display.Handler','Display property type class handler.','true'),
(10005,'PropertyType.List.Display.Id','Display property type id.','false'),
(10006,'PropertyType.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(10007,'PropertyType.List.FilterBy.Category','Filter for property type category.',NULL),
(10008,'PropertyType.List.FilterBy.DefaultUnits','Filter for property type default units.',NULL),
(10009,'PropertyType.List.FilterBy.DefaultValue','Filter for property type default value.',NULL),
(10010,'PropertyType.List.FilterBy.Description','Filter for property type description.',NULL),
(10011,'PropertyType.List.FilterBy.Handler','Filter for property type class handler.',NULL),
(10012,'PropertyType.List.FilterBy.Name','Filter for property type name.',NULL),
(11000,'PropertyTypeCategory.List.Display.Description','Display property type category description.','true'),
(11001,'PropertyTypeCategory.List.Display.Id','Display property type category id.','false'),
(11002,'PropertyTypeCategory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(11003,'PropertyTypeCategory.List.FilterBy.Description','Filter for property type category description.',NULL),
(11004,'PropertyTypeCategory.List.FilterBy.Name','Filter for property type category name.',NULL),
(12000,'PropertyTypeHandler.List.Display.Description','Display property type handler description.','true'),
(12001,'PropertyTypeHandler.List.Display.Id','Display property type handler id.','false'),
(12002,'PropertyTypeHandler.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(12003,'PropertyTypeHandler.List.FilterBy.Description','Filter for property type handler description.',NULL),
(12004,'PropertyTypeHandler.List.FilterBy.Name','Filter for property type handler name.',NULL),
(13000,'PropertyValue.List.Display.Description','Display value entry
description.','true'),
(13001,'PropertyValue.List.Display.EnteredOnDateTime','Display value entry entered on date/time.','false'),
(13002,'PropertyValue.List.Display.EnteredByUser','Display value entry entered by user.','false'),
(13003,'PropertyValue.List.Display.Id','Display property value entry id.','false'),
(13004,'PropertyValue.List.Display.IsDynamic','Display dynamic property type designation.','false'),
(13005,'PropertyValue.List.Display.IsUserWriteable','Display user-writeable property type designation.','false'),
(13006,'PropertyValue.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(13007,'PropertyValue.List.Display.Tag','Display property value tag.','true'),
(13008,'PropertyValue.List.Display.TypeCategory','Display property value type category.','false'),
(13009,'PropertyValue.List.Display.Units','Display value units.','false'),
(13010,'PropertyValue.List.FilterBy.Description','Filter for value description.',NULL),
(13011,'PropertyValue.List.FilterBy.EnteredOnDateTime','Filter for value entry entered on date/time.',NULL),
(13012,'PropertyValue.List.FilterBy.EnteredByUser','Filter for value entry entered by user.',NULL),
(13013,'PropertyValue.List.FilterBy.IsDynamic','Filter for dynamic property value designation.',NULL),
(13014,'PropertyValue.List.FilterBy.IsUserWriteable','Filter for user-writeable property value designation.',NULL),
(13015,'PropertyValue.List.FilterBy.Tag','Filter for property value tag.',NULL),
(13016,'PropertyValue.List.FilterBy.Type','Filter for property value type.',NULL),
(13017,'PropertyValue.List.FilterBy.TypeCategory','Filter for property value type category.',NULL),
(13018,'PropertyValue.List.FilterBy.Units','Filter for value units.',NULL),
(13019,'PropertyValue.List.FilterBy.Value','Filter for value entry.',NULL),
(13020,'PropertyValue.List.Display.EffectiveFromDateTime','Display value entry for effective from date/time.','false'),
(13021,'PropertyValue.List.Display.EffectiveToDateTime','Display value entry for effective to date/time.','false'),
(14000,'PropertyValueHistory.List.Display.Description','Display value entry description.','true'),
(14001,'PropertyValueHistory.List.Display.EnteredOnDateTime','Display value entry entered on date/time.','true'),
(14002,'PropertyValueHistory.List.Display.EnteredByUser','Display value entry entered by user.','true'),
(14003,'PropertyValueHistory.List.Display.Id','Display property value entry id.','false'),
(14004,'PropertyValueHistory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(14005,'PropertyValueHistory.List.Display.Tag','Display value tag.','true'),
(14006,'PropertyValueHistory.List.Display.Units','Display value units.','true'),
(14007,'PropertyValueHistory.List.FilterBy.Description','Filter for value description.',NULL),
(14008,'PropertyValueHistory.List.FilterBy.EnteredOnDateTime','Filter for value entry entered on date/time.',NULL),
(14009,'PropertyValueHistory.List.FilterBy.EnteredByUser','Filter for value entry entered by user.',NULL),
(14010,'PropertyValueHistory.List.FilterBy.Tag','Filter for value tag.',NULL),
(14011,'PropertyValueHistory.List.FilterBy.Units','Filter for value units.',NULL),
(14012,'PropertyValueHistory.List.FilterBy.Value','Filter for value entry.',NULL),
(14013,'PropertyValueHistory.List.Display.EffectiveFromDateTime','Display value entry for effective from date/time.','false'),
(14014,'PropertyValueHistory.List.Display.EffectiveToDateTime','Display value entry for effective to date/time.','false'),
(15000,'Search.CaseInsensitive','Case insensitive search.','true'),
(15001,'Search.Display.ItemDomainCatalog','Display search result for catalog items.','true'),
(15002,'Search.Display.ItemDomainInventory','Display search result for inventory items.','true'),
(15003,'Search.Display.ItemDomainLocation','Display search result for location items.','false'),
(15004,'Search.Display.ItemTypes','Display search result for component types.','false'),
(15005,'Search.Display.ItemCategories','Display search result for component type categories.','false'),
(15006,'Search.Display.ItemElements','Display search result for item  elements.','false'),
(15007,'Search.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(15008,'Search.Display.PropertyTypes','Display search result for property types.','false'),
(15009,'Search.Display.PropertyTypeCategories','Display search result for property type categories.','false'),
(15010,'Search.Display.Sources','Display search result for sources.','false'),
(15011,'Search.Display.Users','Display search result for users.','false'),
(15012,'Search.Display.UserGroups','Display search result for user groups.','false'),
(15013,'Search.DisplayItemDomainMachineDesign','Display search result for machine design items','true'),
(15014,'Search.Display.ItemDomainCableCatalog','Display search result for cable catalog items.','true'),
(15015,'Search.Display.ItemDomainCableInventory','Display search result for cable inventory items.','true'),
(15016,'Search.Display.ItemDomainCableDesign','Display search result for cable design items.','true'),
(15017,'Search.Display.ItemDomainMAARC', 'Display search result for MAARC items', 'false'), 
(16000,'Source.List.Display.ContactInfo','Display source contact info.','true'),
(16001,'Source.List.Display.Description','Display source description.','true'),
(16002,'Source.List.Display.Url','Display source URL.','true'),
(16003,'Source.List.Display.Id','Display source id.','false'),
(16004,'Source.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(16005,'Source.List.FilterBy.ContactInfo','Filter for source contact info.',NULL),
(16006,'Source.List.FilterBy.Description','Filter for source description.',NULL),
(16007,'Source.List.FilterBy.Name','Filter for source name.',NULL),
(16008,'Source.List.FilterBy.Url','Filter for source URL.',NULL),
(17000,'UserInfo.List.Display.Description','Display user description.','false'),
(17001,'UserInfo.List.Display.Email','Display user email.','true'),
(17002,'UserInfo.List.Display.FirstName','Display user first name.','true'),
(17003,'UserInfo.List.Display.Id','Display user id.','false'),
(17004,'UserInfo.List.Display.Groups','Display user groups.','true'),
(17005,'UserInfo.List.Display.LastName','Display user last name.','true'),
(17006,'UserInfo.List.Display.MiddleName','Display user middle name.','false'),
(17007,'UserInfo.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(17008,'UserInfo.List.FilterBy.Description','Filter for user description.',NULL),
(17009,'UserInfo.List.FilterBy.Email','Filter for user email.',NULL),
(17010,'UserInfo.List.FilterBy.FirstName','Filter for user first name.',NULL),
(17011,'UserInfo.List.FilterBy.Groups','Filter for user groups.',NULL),
(17012,'UserInfo.List.FilterBy.LastName','Filter for user last name.',NULL),
(17013,'UserInfo.List.FilterBy.MiddleName','Filter for user middle name.',NULL),
(17014,'UserInfo.List.FilterBy.Username','Filter for username.',NULL),
(18000,'UserGroup.List.Display.Description','Display user group description.','true'),
(18001,'UserGroup.List.Display.Id','Display user group id.','false'),
(18002,'UserGroup.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(18003,'UserGroup.List.FilterBy.Description','Filter for user group description.',NULL),
(18004,'UserGroup.List.FilterBy.Name','Filter for user group name.',NULL),
(19000,'UserSetting.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(20000,'ItemProject.System.ItemProjectId','Default item project to be used in the system',NULL),
(21000,'ItemDomainMachineDesign.List.Display.CreatedByUser','Display created by username.','false'),
(21001,'ItemDomainMachineDesign.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(21002,'ItemDomainMachineDesign.List.Display.OwnerUser','Display owner username.','false'),
(21003,'ItemDomainMachineDesign.List.Display.OwnerGroup','Display owner group name.','false'),
(21004,'ItemDomainMachineDesign.List.Display.Description','Display component description.','true'),
(21005,'ItemDomainMachineDesign.List.Display.Id','Display component id.','false'),
(21006,'ItemDomainMachineDesign.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(21007,'ItemDomainMachineDesign.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(21008,'ItemDomainMachineDesign.List.Display.Location','Display column for location in machine design list.','true'),
(21009,'ItemDomainMachineDesign.List.Display.LocationDetails','Display column for location details in machine design list.','false'),
(21010,'ItemDomainMachineDesign.List.Display.ItemProject','Display column for project in machine design list.','false'),
(21011,'ItemDomainMachineDesign.List.Display.AlternateName','Display column for alternate name in machine design list.','false'),
(21012,'ItemDomainMachineDesign.List.Display.InstalledQrId','Display column for installed qrid in machine design list.','true'),
(21013,'ItemDomainMachineDesign.List.Display.QrId','Display column for qrid in machine design list.','false'),
(21014,'ItemDomainMachineDesign.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(21015,'ItemDomainMachineDesign.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(21016,'ItemDomainMachineDesign.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(21017,'ItemDomainMachineDesign.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(21018,'ItemDomainMachineDesign.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(21019,'ItemDomainMachineDesign.List.Filter.FilteredMachineIds', 'Comma seperated list of top level ids that are filtered by default', ''), 
(21020,'ItemDomainMachineDesign.List.FilterBy.Name','Filter for machine by name.',NULL),
(21021,'ItemDomainMachineDesign.List.Display.MaximumNumberOfSearchResults','Display maximum number of result rows for a machine filter.','600'),
(21200,'ItemDomainMachineDesignInventory.List.Display.CreatedByUser','Display created by username.','false'),
(21201,'ItemDomainMachineDesignInventory.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(21202,'ItemDomainMachineDesignInventory.List.Display.OwnerUser','Display owner username.','false'),
(21203,'ItemDomainMachineDesignInventory.List.Display.OwnerGroup','Display owner group name.','false'),
(21204,'ItemDomainMachineDesignInventory.List.Display.Description','Display component description.','true'),
(21205,'ItemDomainMachineDesignInventory.List.Display.Id','Display component id.','false'),
(21206,'ItemDomainMachineDesignInventory.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(21207,'ItemDomainMachineDesignInventory.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(21208,'ItemDomainMachineDesignInventory.List.Display.Location','Display column for location in machine design list.','true'),
(21209,'ItemDomainMachineDesignInventory.List.Display.LocationDetails','Display column for location details in machine design list.','false'),
(21210,'ItemDomainMachineDesignInventory.List.Display.ItemProject','Display column for project in machine design list.','false'),
(21211,'ItemDomainMachineDesignInventory.List.Display.AlternateName','Display column for alternate name in machine design list.','false'),
(21212,'ItemDomainMachineDesignInventory.List.Display.QrId','Display column for QrId in machine design list.','true'),
(21213,'ItemDomainMachineDesignInventory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(21214,'ItemDomainMachineDesignInventory.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(21215,'ItemDomainMachineDesignInventory.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(21216,'ItemDomainMachineDesignInventory.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(21217,'ItemDomainMachineDesignInventory.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(21218,'ItemDomainMachineDesignInventory.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(21300,'ItemDomainMachineDesignDeletedItems.List.Display.CreatedByUser','Display created by username.','false'),
(21301,'ItemDomainMachineDesignDeletedItems.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(21302,'ItemDomainMachineDesignDeletedItems.List.Display.OwnerUser','Display owner username.','false'),
(21303,'ItemDomainMachineDesignDeletedItems.List.Display.OwnerGroup','Display owner group name.','false'),
(21304,'ItemDomainMachineDesignDeletedItems.List.Display.Description','Display component description.','true'),
(21305,'ItemDomainMachineDesignDeletedItems.List.Display.Id','Display component id.','false'),
(21306,'ItemDomainMachineDesignDeletedItems.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(21307,'ItemDomainMachineDesignDeletedItems.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(21308,'ItemDomainMachineDesignDeletedItems.List.Display.Location','Display column for location in machine design list.','true'),
(21309,'ItemDomainMachineDesignDeletedItems.List.Display.LocationDetails','Display column for location details in machine design list.','false'),
(21310,'ItemDomainMachineDesignDeletedItems.List.Display.ItemProject','Display column for project in machine design list.','false'),
(21311,'ItemDomainMachineDesignDeletedItems.List.Display.AlternateName','Display column for alternate name in machine design list.','false'),
(21312,'ItemDomainMachineDesignDeletedItems.List.Display.QrId','Display column for QrId in machine design list.','true'),
(21313,'ItemDomainMachineDesignDeletedItems.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(21400,'ItemDomainMachineDesignControl.List.Display.CreatedByUser','Display created by username.','false'),
(21401,'ItemDomainMachineDesignControl.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(21402,'ItemDomainMachineDesignControl.List.Display.OwnerUser','Display owner username.','false'),
(21403,'ItemDomainMachineDesignControl.List.Display.OwnerGroup','Display owner group name.','false'),
(21404,'ItemDomainMachineDesignControl.List.Display.Description','Display component description.','true'),
(21405,'ItemDomainMachineDesignControl.List.Display.Id','Display component id.','false'),
(21406,'ItemDomainMachineDesignControl.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(21407,'ItemDomainMachineDesignControl.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(21408,'ItemDomainMachineDesignControl.List.Display.Location','Display column for location in machine design list.','true'),
(21409,'ItemDomainMachineDesignControl.List.Display.LocationDetails','Display column for location details in machine design list.','false'),
(21410,'ItemDomainMachineDesignControl.List.Display.ItemProject','Display column for project in machine design list.','false'),
(21411,'ItemDomainMachineDesignControl.List.Display.AlternateName','Display column for alternate name in machine design list.','false'),
(21412,'ItemDomainMachineDesignControl.List.Display.QrId','Display column for QrId in machine design list.','true'),
(21413,'ItemDomainMachineDesignControl.List.Display.Housing','Display column for housing.','true'),
(21414,'ItemDomainMachineDesignControl.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(21415,'ItemDomainMachineDesignControl.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(21416,'ItemDomainMachineDesignControl.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(21417,'ItemDomainMachineDesignControl.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(21418,'ItemDomainMachineDesignControl.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(21419,'ItemDomainMachineDesignControl.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(22000,'ItemDomainMAARC.List.Display.NumberOfItemsPerPage', 'Display specified number of items per page.','25'),
(22001,'ItemDomainMAARC.List.Display.Id','Display component id.','false'),
(22002,'ItemDomainMAARC.List.Display.EntityTypes','Display Item Entity Types','true'),
(22003,'ItemDomainMAARC.List.Display.Description','Filter for components by description.',NULL),
(22004,'ItemDomainMAARC.List.Display.OwnerUser','Display owner username.','false'),
(22005,'ItemDomainMAARC.List.Display.OwnerGroup','Display owner group name.','false'),
(22006,'ItemDomainMAARC.List.Display.CreatedByUser','Display created by username.','false'),
(22007,'ItemDomainMAARC.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(22008,'ItemDomainMAARC.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(22009,'ItemDomainMAARC.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(22010,'ItemDomainMAARC.List.AutoLoad.FilterBy.Properties','Automatically load component instance list with display properties for filtering.','true'),
(22011,'ItemDomainMAARC.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(22012,'ItemDomainMAARC.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(22013,'ItemDomainMAARC.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(22014,'ItemDomainMAARC.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(22015,'ItemDomainMAARC.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(22016,'ItemDomainMAARC.List.Display.RowExpansion','Display row expansion.','false'),
(22017,'ItemDomainMAARC.List.Load.RowExpansionPropertyValue','Load property values for row expansions.','false'),
(22018,'ItemDomainMAARC.List.Load.FilterDataTable','Automatically load list filter values in data table on page load.','true'),
(22019,'ItemDomainMAARC.List.FilterBy.Name','Filter for components by name.',NULL),
(22020,'ItemDomainMAARC.List.FilterBy.Description','Filter for components by description.',NULL),
(22021,'ItemDomainMAARC.List.FilterBy.OwnerUser','Filter for components by owner username.',NULL),
(22022,'ItemDomainMAARC.List.FilterBy.OwnerGroup','Filter for components by owner group name.',NULL),
(22023,'ItemDomainMAARC.List.FilterBy.CreatedByUser','Filter for components that were created by username.',NULL),
(22024,'ItemDomainMAARC.List.FilterBy.CreatedOnDateTime','Filter for components that were created on date/time.',NULL),
(22025,'ItemDomainMAARC.List.FilterBy.LastModifiedByUser','Filter for components that were last modified by username.',NULL),
(22026,'ItemDomainMAARC.List.FilterBy.LastModifiedOnDateTime','Filter for components that were last modified on date/time.',NULL),
(22027,'ItemDomainMAARC.List.FilterBy.PropertyValue1','Filter for property value with displayed property type id #1.',''),
(22028,'ItemDomainMAARC.List.FilterBy.PropertyValue2','Filter for property value with displayed property type id #2.',''),
(22029,'ItemDomainMAARC.List.FilterBy.PropertyValue3','Filter for property value with displayed property type id #3.',''),
(22030,'ItemDomainMAARC.List.FilterBy.PropertyValue4','Filter for property value with displayed property type id #4.',''),
(22031,'ItemDomainMAARC.List.FilterBy.PropertyValue5','Filter for property value with displayed property type id #5.',''),
(22032,'ItemDomainMAARC.ItemElementList.Display.NumberOfItemsPerPage','Display specified number of items per page for elements.','10'),
(22033,'ItemDomainMAARC.List.FilterBy.ItemEntityType','Filter for item entity type for items.','Measurement Data'),
(23000,'ItemDomainCableDesign.List.Display.CreatedByUser','Display created by username.','false'),
(23001,'ItemDomainCableDesign.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(23002,'ItemDomainCableDesign.List.Display.OwnerUser','Display owner username.','false'),
(23003,'ItemDomainCableDesign.List.Display.OwnerGroup','Display owner group name.','false'),
(23004,'ItemDomainCableDesign.List.Display.Description','Display component description.','true'),
(23005,'ItemDomainCableDesign.List.Display.Id','Display component id.','false'),
(23006,'ItemDomainCableDesign.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(23007,'ItemDomainCableDesign.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(23008,'ItemDomainCableDesign.List.Display.Location','Display column for location in machine design list.','true'),
(23009,'ItemDomainCableDesign.List.Display.LocationDetails','Display column for location details in machine design list.','false'),
(23010,'ItemDomainCableDesign.List.Display.ItemProject','Display column for project in machine design list.','false'),
(23011,'ItemDomainCableDesign.List.Display.ItemIdentifier1','Display column for alternate name in machine design list.','false'),
(23012,'ItemDomainCableDesign.List.Display.Endpoints','Display column for endpoints in cable design list.','true'),
(23013,'ItemDomainCableDesign.List.Display.CatalogItem','Display column for assigned catalog item in cable  design list.','true'),
(23014,'ItemDomainCableDesign.List.Display.Laying','Display column for laying in cable design list.','false'),
(23015,'ItemDomainCableDesign.List.Display.Voltage','Display column for voltage in cable design list.','false'),
(23016,'ItemDomainCableDesign.List.FilterBy.Endpoints','Filter for components by endpoints.',NULL),
(23017,'ItemDomainCableDesign.List.FilterBy.CatalogItem','Filter for components by catalog item.',NULL),
(23018,'ItemDomainCableDesign.List.FilterBy.Laying','Filter for components by laying.',NULL),
(23019,'ItemDomainCableDesign.List.FilterBy.Voltage','Filter for components by voltage.',NULL),
(23020,'ItemDomainCableDesign.List.Load.FilterDataTable','Automatically load list filter values in data table on page load.','true'),
(23021,'ItemDomainCableDesign.List.Display.ItemCategory','Display column for technical system in cable design list.','true'),
(23022,'ItemDomainCableDesign.List.Display.ExternalCableName','Display external cable name.','false'),
(23023,'ItemDomainCableDesign.List.FilterBy.ExternalCableName','FilterBy external cable name.',''),
(23024,'ItemDomainCableDesign.List.Display.ImportCableId','Display import cable id.','false'),
(23025,'ItemDomainCableDesign.List.FilterBy.ImportCableId','FilterBy import cable id.',''),
(23026,'ItemDomainCableDesign.List.Display.AlternateCableId','Display alternate cable id.','false'),
(23027,'ItemDomainCableDesign.List.FilterBy.AlternateCableId','FilterBy alternate cable id.',''),
(23028,'ItemDomainCableDesign.List.Display.DescriptionEndpoint1','Display DescriptionEndpoint1.','false'),
(23029,'ItemDomainCableDesign.List.FilterBy.DescriptionEndpoint1','FilterBy DescriptionEndpoint1.',''),
(23030,'ItemDomainCableDesign.List.Display.DescriptionEndpoint2','Display DescriptionEndpoint2.','false'),
(23031,'ItemDomainCableDesign.List.FilterBy.DescriptionEndpoint2','FilterBy DescriptionEndpoint2.',''),
(23032,'ItemDomainCableDesign.List.Display.LegacyQrId','Display legacy QR id.','false'),
(23033,'ItemDomainCableDesign.List.FilterBy.LegacyQrId','FilterBy legacy QR id.',''),
(23034,'ItemDomainCableDesign.List.Display.RouteEndpoint1','Display RouteEndpoint1.','false'),
(23035,'ItemDomainCableDesign.List.FilterBy.RouteEndpoint1','FilterBy RouteEndpoint1.',''),
(23036,'ItemDomainCableDesign.List.Display.RouteEndpoint2','Display RouteEndpoint2.','false'),
(23037,'ItemDomainCableDesign.List.FilterBy.RouteEndpoint2','FilterBy RouteEndpoint2.',''),
(23038,'ItemDomainCableDesign.List.Display.RoutedLength','Display routed length.','false'),
(23039,'ItemDomainCableDesign.List.FilterBy.RoutedLength','FilterBy routed length.',''),
(23040,'ItemDomainCableDesign.List.Display.Route','Display route.','false'),
(23041,'ItemDomainCableDesign.List.FilterBy.Route','FilterBy route.',''),
(23042,'ItemDomainCableDesign.List.Display.Notes','Display notes.','false'),
(23043,'ItemDomainCableDesign.List.FilterBy.Notes','FilterBy notes.',''),
(23044,'ItemDomainCableDesign.List.Display.EndLengthEndpoint1','Display EndLengthEndpoint1.','false'),
(23045,'ItemDomainCableDesign.List.FilterBy.EndLengthEndpoint1','FilterBy EndLengthEndpoint1.',''),
(23046,'ItemDomainCableDesign.List.Display.TerminationEndpoint1','Display TerminationEndpoint1.','false'),
(23047,'ItemDomainCableDesign.List.FilterBy.TerminationEndpoint1','FilterBy TerminationEndpoint1.',''),
(23048,'ItemDomainCableDesign.List.Display.PinlistEndpoint1','Display PinlistEndpoint1.','false'),
(23049,'ItemDomainCableDesign.List.FilterBy.PinlistEndpoint1','FilterBy PinlistEndpoint1.',''),
(23050,'ItemDomainCableDesign.List.Display.NotesEndpoint1','Display NotesEndpoint1.','false'),
(23051,'ItemDomainCableDesign.List.FilterBy.NotesEndpoint1','FilterBy NotesEndpoint1.',''),
(23052,'ItemDomainCableDesign.List.Display.DrawingEndpoint1','Display DrawingEndpoint1.','false'),
(23053,'ItemDomainCableDesign.List.FilterBy.DrawingEndpoint1','FilterBy DrawingEndpoint1.',''),
(23054,'ItemDomainCableDesign.List.Display.EndLengthEndpoint2','Display EndLengthEndpoint2.','false'),
(23055,'ItemDomainCableDesign.List.FilterBy.EndLengthEndpoint2','FilterBy EndLengthEndpoint2.',''),
(23056,'ItemDomainCableDesign.List.Display.TerminationEndpoint2','Display TerminationEndpoint2.','false'),
(23057,'ItemDomainCableDesign.List.FilterBy.TerminationEndpoint2','FilterBy TerminationEndpoint2.',''),
(23058,'ItemDomainCableDesign.List.Display.PinlistEndpoint2','Display PinlistEndpoint2.','false'),
(23059,'ItemDomainCableDesign.List.FilterBy.PinlistEndpoint2','FilterBy PinlistEndpoint2.',''),
(23060,'ItemDomainCableDesign.List.Display.NotesEndpoint2','Display NotesEndpoint2.','false'),
(23061,'ItemDomainCableDesign.List.FilterBy.NotesEndpoint2','FilterBy NotesEndpoint2.',''),
(23062,'ItemDomainCableDesign.List.Display.DrawingEndpoint2','Display DrawingEndpoint2.','false'),
(23063,'ItemDomainCableDesign.List.FilterBy.DrawingEndpoint2','FilterBy DrawingEndpoint2.',''),
(23064,'ItemDomainCableDesign.List.Display.DeviceEndpoint1','Display DeviceEndpoint1.','false'),
(23065,'ItemDomainCableDesign.List.FilterBy.DeviceEndpoint1','FilterBy DeviceEndpoint1.',''),
(23066,'ItemDomainCableDesign.List.Display.PortEndpoint1','Display PortEndpoint1.','false'),
(23067,'ItemDomainCableDesign.List.FilterBy.PortEndpoint1','FilterBy PortEndpoint1.',''),
(23068,'ItemDomainCableDesign.List.Display.ConnectorEndpoint1','Display ConnectorEndpoint1.','false'),
(23069,'ItemDomainCableDesign.List.FilterBy.ConnectorEndpoint1','FilterBy ConnectorEndpoint1.',''),
(23070,'ItemDomainCableDesign.List.Display.DeviceEndpoint2','Display DeviceEndpoint2.','false'),
(23071,'ItemDomainCableDesign.List.FilterBy.DeviceEndpoint2','FilterBy DeviceEndpoint2.',''),
(23072,'ItemDomainCableDesign.List.Display.PortEndpoint2','Display PortEndpoint2.','false'),
(23073,'ItemDomainCableDesign.List.FilterBy.PortEndpoint2','FilterBy PortEndpoint2.',''),
(23074,'ItemDomainCableDesign.List.Display.ConnectorEndpoint2','Display ConnectorEndpoint2.','false'),
(23075,'ItemDomainCableDesign.List.FilterBy.ConnectorEndpoint2','FilterBy ConnectorEndpoint2.',''),
(23076,'ItemDomainCableDesign.List.Display.ConnectedDevicesEndpoint1','Display ConnectedDevicesEndpoint1.','false'),
(23077,'ItemDomainCableDesign.List.FilterBy.ConnectedDevicesEndpoint1','FilterBy ConnectedDevicesEndpoint1.',''),
(23078,'ItemDomainCableDesign.List.Display.ConnectedDevicesEndpoint2','Display ConnectedDevicesEndpoint2.','false'),
(23079,'ItemDomainCableDesign.List.FilterBy.ConnectedDevicesEndpoint2','FilterBy ConnectedDevicesEndpoint2.',''),
(23080,'ItemDomainCableDesign.List.Display.LocationEndpoint1','Display LocationEndpoint1.','false'),
(23081,'ItemDomainCableDesign.List.FilterBy.LocationEndpoint1','FilterBy LocationEndpoint1.',''),
(23082,'ItemDomainCableDesign.List.Display.LocationEndpoint2','Display LocationEndpoint2.','false'),
(23083,'ItemDomainCableDesign.List.FilterBy.LocationEndpoint2','FilterBy LocationEndpoint2.',''),
(23084,'ItemDomainCableDesign.List.Display.AssignedInventory','Display column for assigned inventory in cable design list.','true'),
(23085,'ItemDomainCableDesign.List.Display.InstallationStatus','Display column for installation status in cable  design list.','true'),
(23086,'ItemDomainCableDesign.List.FilterBy.AssignedInventory','Filter for components by assigned inventory.',NULL),
(23087,'ItemDomainCableDesign.List.FilterBy.InstallationStatus','Filter for components by installation status.',NULL),
(23088,'ItemDomainCableDesign.List.Display.TotalReqLengthDisplay','Display total required cable length.','false'),
(23089,'ItemDomainCableDesign.List.FilterBy.TotalReqLengthDisplay','Filter for total required cable length.',NULL),
(24000,'ItemDomainCableCatalog.List.AutoLoad.FilterBy.Properties','Automatically load component list with display properties for filtering.','true'),
(24001,'ItemDomainCableCatalog.List.Display.ItemCategory','Display catalog item category.','true'),
(24002,'ItemDomainCableCatalog.List.Display.CreatedByUser','Display created by username.','false'),
(24003,'ItemDomainCableCatalog.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(24004,'ItemDomainCableCatalog.List.Display.Description','Display component description.','true'),
(24005,'ItemDomainCableCatalog.List.Display.Id','Display component id.','false'),
(24006,'ItemDomainCableCatalog.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(24007,'ItemDomainCableCatalog.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(24008,'ItemDomainCableCatalog.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(24009,'ItemDomainCableCatalog.List.Display.ItemIdentifier1','Display component model number.','true'),
(24010,'ItemDomainCableCatalog.List.Display.OwnerUser','Display owner username.','false'),
(24011,'ItemDomainCableCatalog.List.Display.OwnerGroup','Display owner group name.','false'),
(24012,'ItemDomainCableCatalog.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(24013,'ItemDomainCableCatalog.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(24014,'ItemDomainCableCatalog.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(24015,'ItemDomainCableCatalog.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(24016,'ItemDomainCableCatalog.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(24017,'ItemDomainCableCatalog.List.Display.Sources','Display component sources.','false'),
(24022,'ItemDomainCableCatalog.List.Display.Project','Display Item Project','false'),
(24026,'ItemDomainCableCatalog.List.FilterBy.ItemCategory','Filter for components by type category.',NULL),
(24027,'ItemDomainCableCatalog.List.FilterBy.CreatedByUser','Filter for components that were created by username.',NULL),
(24028,'ItemDomainCableCatalog.List.FilterBy.CreatedOnDateTime','Filter for components that were created on date/time.',NULL),
(24029,'ItemDomainCableCatalog.List.FilterBy.Description','Filter for components by description.',NULL),
(24030,'ItemDomainCableCatalog.List.FilterBy.LastModifiedByUser','Filter for components that were last modified by username.',NULL),
(24031,'ItemDomainCableCatalog.List.FilterBy.LastModifiedOnDateTime','Filter for components that were last modified on date/time.',NULL),
(24032,'ItemDomainCableCatalog.List.FilterBy.ItemIdentifier1','Filter for component model number.',NULL),
(24033,'ItemDomainCableCatalog.List.FilterBy.PropertyValue1','Filter for property value with displayed property type id #1.',''),
(24034,'ItemDomainCableCatalog.List.FilterBy.PropertyValue2','Filter for property value with displayed property type id #2.',''),
(24035,'ItemDomainCableCatalog.List.FilterBy.PropertyValue3','Filter for property value with displayed property type id #3.',''),
(24036,'ItemDomainCableCatalog.List.FilterBy.PropertyValue4','Filter for property value with displayed property type id #4.',''),
(24037,'ItemDomainCableCatalog.List.FilterBy.PropertyValue5','Filter for property value with displayed property type id #5.',''),
(24038,'ItemDomainCableCatalog.List.FilterBy.Name','Filter for components by name.',NULL),
(24039,'ItemDomainCableCatalog.List.FilterBy.OwnerUser','Filter for components by owner username.',NULL),
(24040,'ItemDomainCableCatalog.List.FilterBy.OwnerGroup','Filter for components by owner group name.',NULL),
(24041,'ItemDomainCableCatalog.List.FilterBy.Sources','Filter for components by sources.',NULL),
(24047,'ItemDomainCableCatalog.List.Load.FilterDataTable','Automatically load list filter values in data table on page load.','true'),
(24048,'ItemDomainCableCatalog.List.Display.HeatLimit','Display component heat limit.','false'),
(24049,'ItemDomainCableCatalog.List.Display.Insulation','Display component insulation.','false'),
(24050,'ItemDomainCableCatalog.List.Display.JacketColor','Display component jacket color.','false'),
(24051,'ItemDomainCableCatalog.List.Display.Weight','Display component weight.','false'),
(24052,'ItemDomainCableCatalog.List.Display.Diameter','Display component diameter.','false'),
(24053,'ItemDomainCableCatalog.List.Display.Url','Display component Url.','false'),
(24054,'ItemDomainCableCatalog.List.Display.BendRadius','Display component bend radius.','false'),
(24055,'ItemDomainCableCatalog.List.Display.RadiationTolerance','Display component radiation tolerance.','false'),
(24056,'ItemDomainCableCatalog.List.Display.Conductors','Display component conductors.','false'),
(24057,'ItemDomainCableCatalog.List.Display.ImageUrl','Display component image url.','false'),
(24058,'ItemDomainCableCatalog.List.Display.FireLoad','Display component fire load.','false'),
(24059,'ItemDomainCableCatalog.List.Display.VoltageRating','Display component voltage rating.','false'),
(24060,'ItemDomainCableCatalog.List.FilterBy.HeatLimit','FilterBy component heat limit.',''),
(24061,'ItemDomainCableCatalog.List.FilterBy.Insulation','FilterBy component insulation.',''),
(24062,'ItemDomainCableCatalog.List.FilterBy.JacketColor','FilterBy component jacket color.',''),
(24063,'ItemDomainCableCatalog.List.FilterBy.Weight','FilterBy component weight.',''),
(24064,'ItemDomainCableCatalog.List.FilterBy.Diameter','FilterBy component diameter.',''),
(24065,'ItemDomainCableCatalog.List.FilterBy.Url','FilterBy component Url.',''),
(24066,'ItemDomainCableCatalog.List.FilterBy.BendRadius','FilterBy component bend radius.',''),
(24067,'ItemDomainCableCatalog.List.FilterBy.RadiationTolerance','FilterBy component radiation tolerance.',''),
(24068,'ItemDomainCableCatalog.List.FilterBy.Conductors','FilterBy component conductors.',''),
(24069,'ItemDomainCableCatalog.List.FilterBy.ImageUrl','FilterBy component image url.',''),
(24070,'ItemDomainCableCatalog.List.FilterBy.FireLoad','FilterBy component fire load.',''),
(24071,'ItemDomainCableCatalog.List.FilterBy.VoltageRating','FilterBy component voltage rating.',''),
(24072,'ItemDomainCableCatalog.List.Display.AltPartNumber','Display alt part number.','false'),
(24073,'ItemDomainCableCatalog.List.FilterBy.AltPartNumber','FilterBy alt part number.',''),
(24074,'ItemDomainCableCatalog.List.Display.TotalLength','Display component total length.','false'),
(24075,'ItemDomainCableCatalog.List.FilterBy.TotalLength','FilterBy component total length.',''),
(24076,'ItemDomainCableCatalog.List.Display.ReelLength','Display component reel length.','false'),
(24077,'ItemDomainCableCatalog.List.FilterBy.ReelLength','FilterBy component reel length.',''),
(24078,'ItemDomainCableCatalog.List.Display.ReelQuantity','Display component reel quantity.','false'),
(24079,'ItemDomainCableCatalog.List.FilterBy.ReelQuantity','FilterBy component reel quantity.',''),
(24080,'ItemDomainCableCatalog.List.Display.LeadTime','Display component lead time.','false'),
(24081,'ItemDomainCableCatalog.List.FilterBy.LeadTime','FilterBy component lead time.',''),
(24082,'ItemDomainCableCatalog.List.Display.ProcurementStatus','Display component procurement status.','false'),
(24083,'ItemDomainCableCatalog.List.FilterBy.ProcurementStatus','FilterBy component procurement status.',''),
(24084,'ItemDomainCableCatalog.List.Display.RowExpansion','Display row expansion.','true'),
(24085,'ItemDomainCableCatalog.List.Display.ComponentInstance.RowExpansion','Display Component Instance row expansion.','true'),
(24086,'ItemDomainCableCatalog.List.Load.ComponentInstance.RowExpansionPropertyValue','Load property values for component instance row expansions.','false'),
(24087,'ItemDomainCableCatalog.Help.ListPage.Display.Fragment','Display Help guide to the user on the main list page of the Component entity.','true'),
(24088,'ItemDomainCableCatalog.List.Scope.Display','Show list page with a scope applied.','All'),
(24089,'ItemDomainCableCatalog.List.Scope.Display.PropertyTypeId','Setting used along side a display scope of property type.',NULL),
(24090,'ItemDomainCableCatalog.List.Load.RowExpansionPropertyValue','Load property values for row expansions.','false'),
(25000,'ItemDomainCableInventory.List.AutoLoad.FilterBy.Properties','Automatically load component instance list with display properties for filtering.','true'),
(25001,'ItemDomainCableInventory.List.Display.CreatedByUser','Display created by username.','false'),
(25002,'ItemDomainCableInventory.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(25003,'ItemDomainCableInventory.List.Display.Description','Display component instance description.','false'),
(25004,'ItemDomainCableInventory.List.Display.Id','Display component instance id.','false'),
(25005,'ItemDomainCableInventory.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(25006,'ItemDomainCableInventory.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(25007,'ItemDomainCableInventory.List.Display.Location','Display inventory item location.','true'),
(25008,'ItemDomainCableInventory.List.Display.LocationDetails','Display component instance location details.','false'),
(25009,'ItemDomainCableInventory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(25010,'ItemDomainCableInventory.List.Display.OwnerUser','Display owner username.','false'),
(25011,'ItemDomainCableInventory.List.Display.OwnerGroup','Display owner group name.','false'),
(25012,'ItemDomainCableInventory.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(25013,'ItemDomainCableInventory.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(25014,'ItemDomainCableInventory.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(25015,'ItemDomainCableInventory.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(25016,'ItemDomainCableInventory.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(25017,'ItemDomainCableInventory.List.Display.QrId','Display component instance QR id.','true'),
(25018,'ItemDomainCableInventory.List.Display.SerialNumber','Display component instance serial number.','false'),
(25019,'ItemDomainCableInventory.List.Display.Project','Display Inventory Item project.','false'),
(25021,'ItemDomainCableInventory.List.Display.RowExpansion','Display row expansion.','true'),
(25022,'ItemDomainCableInventory.List.Load.RowExpansionPropertyValue','Load property values for row expansions.','false'),
(25024,'ItemDomainCableInventory.List.FilterBy.CreatedByUser','Filter for components that were created by username.',NULL),
(25025,'ItemDomainCableInventory.List.FilterBy.CreatedOnDateTime','Filter for components that were created on date/time.',NULL),
(25026,'ItemDomainCableInventory.List.FilterBy.Description','Filter for components by description.',NULL),
(25027,'ItemDomainCableInventory.List.FilterBy.LastModifiedByUser','Filter for components that were last modified by username.',NULL),
(25028,'ItemDomainCableInventory.List.FilterBy.LastModifiedOnDateTime','Filter for components that were last modified on date/time.',NULL),
(25029,'ItemDomainCableInventory.List.FilterBy.Location','Filter for component instance location.',NULL),
(25030,'ItemDomainCableInventory.List.FilterBy.LocationDetails','Filter for component instance location details.',NULL),
(25031,'ItemDomainCableInventory.List.FilterBy.OwnerUser','Filter for component instances by owner username.',NULL),
(25032,'ItemDomainCableInventory.List.FilterBy.OwnerGroup','Filter for component instances by owner group name.',NULL),
(25033,'ItemDomainCableInventory.List.FilterBy.PropertyValue1','Filter for property value with displayed property type id #1.',''),
(25034,'ItemDomainCableInventory.List.FilterBy.PropertyValue2','Filter for property value with displayed property type id #2.',''),
(25035,'ItemDomainCableInventory.List.FilterBy.PropertyValue3','Filter for property value with displayed property type id #3.',''),
(25036,'ItemDomainCableInventory.List.FilterBy.PropertyValue4','Filter for property value with displayed property type id #4.',''),
(25037,'ItemDomainCableInventory.List.FilterBy.PropertyValue5','Filter for property value with displayed property type id #5.',''),
(25038,'ItemDomainCableInventory.List.FilterBy.QrId','Filter for component instance QR id.',NULL),
(25039,'ItemDomainCableInventory.List.FilterBy.SerialNumber','Filter for component instance serial number.',NULL),
(25040,'ItemDomainCableInventory.List.FilterBy.Tag','Filter for component instance tag.',NULL),
(25041,'ItemDomainCableInventory.Help.ListPage.Display.Fragment','Display Help guide to the user on the main list page of the Component Instance entity.','true'),
(25042,'ItemDomainCableInventory.List.Scope.Display','Show list page with a scope applied.','All'),
(25043,'ItemDomainCableInventory.List.Scope.Display.PropertyTypeId','Setting used along side a display scope of property type.',NULL),
(25045,'ItemDomainCableInventory.List.Load.FilterDataTable','Automatically load list filter values in data table on page load.','true'),
(25046,'ItemDomainCableInventory.List.Display.Length','Display column for length in cable inventory list.','true'),
(25047,'ItemDomainCableInventory.List.FilterBy.Length','Filter for components by length.',NULL),
(25048,'ItemDomainCableInventory.List.FilterBy.Status','Filter for components by status.',NULL),
(25049,'ItemDomainCableInventory.List.Display.Status','Display column for status in cable inventory list.','true');
/*!40000 ALTER TABLE `setting_type` ENABLE KEYS */;
UNLOCK TABLES;
