{% set name = "ComponentDB-CLI" %}
{% set version = "3.14.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: cb89b432539d6a9272d991e81dbb74551cd59f271e5733585babbb95f3b4b595 
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
   - python
   - pip
  run:
    - python
    - python-dateutil
    - urllib3
    - six    
    - click
    - pandas
    - rich    
    - InquirerPy
    - paho-mqtt    
    - componentdb-api=={{ version }}

test:
  imports:
    - cdbCli

about:
  home: "https://github.com/AdvancedPhotonSource/ComponentDB"
  license: "Copyright (c) UChicago Argonne, LLC. All rights reserved."    
  summary: "Command line utilities for Component DB"
