{% set name = "ComponentDB-CLI" %}
{% set version = "3.16.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 0
  noarch: python  
  script: {{ PYTHON }} -m pip install . --no-deps

requirements:
  build:
    - python>=3.10
    - setuptools
    - pip
  run:
    - python
    - python-dateutil
    - urllib3
    - six    
    - click
    - pandas
    - rich    
    - InquirerPy
    - paho-mqtt    
    - componentdb-api=={{ version }}


test:
  imports:
    - cdbCli

about:
  home: "https://github.com/AdvancedPhotonSource/ComponentDB"
  license: "Copyright (c) UChicago Argonne, LLC. All rights reserved."    
  summary: "Command line utilities for Component DB"
