# coding: utf-8

"""
    Component Database API

    The API that provides access to Component Database data.  # noqa: E501

    The version of the OpenAPI document: 3.12.3
    Contact: djarosz@anl.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cdbApi.configuration import Configuration


class ItemMembership(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'part_of_item': 'Item',
        'represented_by': 'ItemElement'
    }

    attribute_map = {
        'part_of_item': 'partOfItem',
        'represented_by': 'representedBy'
    }

    def __init__(self, part_of_item=None, represented_by=None, local_vars_configuration=None):  # noqa: E501
        """ItemMembership - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._part_of_item = None
        self._represented_by = None
        self.discriminator = None

        if part_of_item is not None:
            self.part_of_item = part_of_item
        if represented_by is not None:
            self.represented_by = represented_by

    @property
    def part_of_item(self):
        """Gets the part_of_item of this ItemMembership.  # noqa: E501


        :return: The part_of_item of this ItemMembership.  # noqa: E501
        :rtype: Item
        """
        return self._part_of_item

    @part_of_item.setter
    def part_of_item(self, part_of_item):
        """Sets the part_of_item of this ItemMembership.


        :param part_of_item: The part_of_item of this ItemMembership.  # noqa: E501
        :type: Item
        """

        self._part_of_item = part_of_item

    @property
    def represented_by(self):
        """Gets the represented_by of this ItemMembership.  # noqa: E501


        :return: The represented_by of this ItemMembership.  # noqa: E501
        :rtype: ItemElement
        """
        return self._represented_by

    @represented_by.setter
    def represented_by(self, represented_by):
        """Sets the represented_by of this ItemMembership.


        :param represented_by: The represented_by of this ItemMembership.  # noqa: E501
        :type: ItemElement
        """

        self._represented_by = represented_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemMembership):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ItemMembership):
            return True

        return self.to_dict() != other.to_dict()
