# coding: utf-8

"""
    Component Database API

    The API that provides access to Component Database data.  # noqa: E501

    The version of the OpenAPI document: 3.12.3
    Contact: djarosz@anl.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cdbApi.configuration import Configuration


class NewCatalogInformation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'model_number': 'str',
        'alternate_name': 'str',
        'description': 'str',
        'technical_system_list': 'list[ItemCategory]',
        'function_list': 'list[ItemType]',
        'item_projects_list': 'list[ItemProject]'
    }

    attribute_map = {
        'name': 'name',
        'model_number': 'modelNumber',
        'alternate_name': 'alternateName',
        'description': 'description',
        'technical_system_list': 'technicalSystemList',
        'function_list': 'functionList',
        'item_projects_list': 'itemProjectsList'
    }

    def __init__(self, name=None, model_number=None, alternate_name=None, description=None, technical_system_list=None, function_list=None, item_projects_list=None, local_vars_configuration=None):  # noqa: E501
        """NewCatalogInformation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._model_number = None
        self._alternate_name = None
        self._description = None
        self._technical_system_list = None
        self._function_list = None
        self._item_projects_list = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if model_number is not None:
            self.model_number = model_number
        if alternate_name is not None:
            self.alternate_name = alternate_name
        if description is not None:
            self.description = description
        if technical_system_list is not None:
            self.technical_system_list = technical_system_list
        if function_list is not None:
            self.function_list = function_list
        if item_projects_list is not None:
            self.item_projects_list = item_projects_list

    @property
    def name(self):
        """Gets the name of this NewCatalogInformation.  # noqa: E501


        :return: The name of this NewCatalogInformation.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NewCatalogInformation.


        :param name: The name of this NewCatalogInformation.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def model_number(self):
        """Gets the model_number of this NewCatalogInformation.  # noqa: E501


        :return: The model_number of this NewCatalogInformation.  # noqa: E501
        :rtype: str
        """
        return self._model_number

    @model_number.setter
    def model_number(self, model_number):
        """Sets the model_number of this NewCatalogInformation.


        :param model_number: The model_number of this NewCatalogInformation.  # noqa: E501
        :type: str
        """

        self._model_number = model_number

    @property
    def alternate_name(self):
        """Gets the alternate_name of this NewCatalogInformation.  # noqa: E501


        :return: The alternate_name of this NewCatalogInformation.  # noqa: E501
        :rtype: str
        """
        return self._alternate_name

    @alternate_name.setter
    def alternate_name(self, alternate_name):
        """Sets the alternate_name of this NewCatalogInformation.


        :param alternate_name: The alternate_name of this NewCatalogInformation.  # noqa: E501
        :type: str
        """

        self._alternate_name = alternate_name

    @property
    def description(self):
        """Gets the description of this NewCatalogInformation.  # noqa: E501


        :return: The description of this NewCatalogInformation.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NewCatalogInformation.


        :param description: The description of this NewCatalogInformation.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def technical_system_list(self):
        """Gets the technical_system_list of this NewCatalogInformation.  # noqa: E501


        :return: The technical_system_list of this NewCatalogInformation.  # noqa: E501
        :rtype: list[ItemCategory]
        """
        return self._technical_system_list

    @technical_system_list.setter
    def technical_system_list(self, technical_system_list):
        """Sets the technical_system_list of this NewCatalogInformation.


        :param technical_system_list: The technical_system_list of this NewCatalogInformation.  # noqa: E501
        :type: list[ItemCategory]
        """

        self._technical_system_list = technical_system_list

    @property
    def function_list(self):
        """Gets the function_list of this NewCatalogInformation.  # noqa: E501


        :return: The function_list of this NewCatalogInformation.  # noqa: E501
        :rtype: list[ItemType]
        """
        return self._function_list

    @function_list.setter
    def function_list(self, function_list):
        """Sets the function_list of this NewCatalogInformation.


        :param function_list: The function_list of this NewCatalogInformation.  # noqa: E501
        :type: list[ItemType]
        """

        self._function_list = function_list

    @property
    def item_projects_list(self):
        """Gets the item_projects_list of this NewCatalogInformation.  # noqa: E501


        :return: The item_projects_list of this NewCatalogInformation.  # noqa: E501
        :rtype: list[ItemProject]
        """
        return self._item_projects_list

    @item_projects_list.setter
    def item_projects_list(self, item_projects_list):
        """Sets the item_projects_list of this NewCatalogInformation.


        :param item_projects_list: The item_projects_list of this NewCatalogInformation.  # noqa: E501
        :type: list[ItemProject]
        """

        self._item_projects_list = item_projects_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewCatalogInformation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NewCatalogInformation):
            return True

        return self.to_dict() != other.to_dict()
