LOCK TABLES `user_info` WRITE;
/*!40000 ALTER TABLE `user_info` DISABLE KEYS */;
INSERT INTO `user_info` VALUES
(1,'cdb','CDB','System Account',NULL,'cdb@aps.anl.gov',NULL,NULL),
(2,'bstill.lock','Ben','Stillwell',NULL,'bstill@aps.anl.gov',NULL,NULL),
(3,'nda','Ned','Arnold',NULL,'nda@aps.anl.gov',NULL,NULL),
(4,'sveseli','Sinisa','Veseli',NULL,'sveseli@aps.anl.gov',NULL,NULL),
(5,'benes.lock','Scott','Benes',NULL,'benes@aps.anl.gov',NULL,NULL),
(6,'nschwarz.lock','Nicholas','Schwarz',NULL,'nschwarz@aps.anl.gov',NULL,NULL),
(7,'cease.lock','Herman','Cease',NULL,'cease@aps.anl.gov',NULL,NULL),
(8,'carwar.lock','John','Carwardine',NULL,'carwar@aps.anl.gov',NULL,NULL),
(9,'decker.lock','Glenn','Decker',NULL,'decker@aps.anl.gov',NULL,NULL),
(10,'ngrossman.lock','Nancy','Grossman',NULL,'ngrossman@aps.anl.gov',NULL,NULL),
(11,'cprokuski.lock','Chuck','Prokuski',NULL,'cprokuski@aps.anl.gov',NULL,NULL),
(12,'jaski.lock','Mark','Jaski',NULL,'jaski@aps.anl.gov',NULL,NULL),
(13,'juw.lock','Ju','Wang',NULL,'juw@aps.anl.gov',NULL,NULL),
(14,'blill.lock','Bob','Lill',NULL,'blill@aps.anl.gov',NULL,NULL),
(15,'horan.lock','Doug','Horan',NULL,'horan@aps.anl.gov',NULL,NULL),
(16,'fornek.lock','Tom','Fornek',NULL,'fornek@aps.anl.gov',NULL,NULL),
(17,'rif.lock','Richard','Farnsworth',NULL,'rif@aps.anl.gov',NULL,NULL),
(18,'frl.lock','Frank','Lenkszus',NULL,'frl@aps.anl.gov',NULL,NULL),
(19,'preissner.lock','Curt','Preissner',NULL,'preissner@aps.anl.gov',NULL,NULL),
(20,'lhm.lock','Leonard','Morrison',NULL,'lhm@aps.anl.gov',NULL,NULL),
(21,'jieliu.lock','Jie','Liu',NULL,'jieliu@aps.anl.gov',NULL,NULL),
(22,'doose.lock','Charles','Doose',NULL,'doose@aps.anl.gov',NULL,NULL),
(23,'tfors.lock','Tom','Fors',NULL,'tfors@aps.anl.gov',NULL,NULL),
(24,'bran.lock','Bran','Brajuskovic',NULL,'bran@aps.anl.gov',NULL,NULL),
(25,'jzientek.lock','John','Zientek',NULL,'jzientek@aps.anl.gov',NULL,NULL),
(26,'djarosz','Dariusz','Jarosz','Piotr','djarosz@aps.anl.gov',NULL,NULL),
(27,'mwhite.lock','Marion','White',NULL,'mwhite@aps.anl.gov',NULL,NULL),
(28,'brianr.lock','Brian','Rusthoven',NULL,'brianr@aps.anl.gov',NULL,NULL),
(29,'shoaf.lock','Steve','Shoaf',NULL,'shoaf@aps.anl.gov',NULL,NULL),
(30,'hbui.lock','Hanh','Bui',NULL,'hbui@aps.anl.gov',NULL,NULL),
(31,'sereno.lock','Nick','Sereno',NULL,'sereno@aps.anl.ogv',NULL,NULL),
(32,'xusf.lock','Shifu','Xu',NULL,'xusf@aps.anl.gov',NULL,NULL),
(33,'afp.lock','Tony','Pietryla',NULL,'afp@aps.anl.gov',NULL,NULL),
(34,'rblake.lock','Ron','Blake',NULL,'rblake@aps.anl.gov',NULL,NULL),
(35,'dejus.lock','Roger','Dejus',NULL,'dejus@aps.anl.gov',NULL,NULL),
(36,'collins.lock','Jeff','Collins',NULL,'collins@aps.anl.gov',NULL,NULL),
(37,'keane.lock','Rob','Keane',NULL,'keane@aps.anl.gov',NULL,NULL),
(38,'jzxu.lock','Joe','Xu',NULL,'jzxu@aps.anl.gov',NULL,NULL),
(39,'jnudell.lock','Jeremy','Nudell',NULL,'jnudell@aps.anl.gov',NULL,NULL),
(40,'borland.lock','Michael','Borland',NULL,'borland@aps.anl.gov',NULL,NULL),
(41,'soprondek.lock','Samuel','Oprondek',NULL,'soprondek@aps.anl.gov',NULL,NULL),
(42,'hanuska.lock','Steve','Hanuska',NULL,'hanuska@aps.anl.gov',NULL,NULL),
(43,'nda1','Ned','Arnold','Local','nda@aps.anl.gov',NULL,NULL),
(44,'jabraham.lock','Josh','Abraham',NULL,'jabraham@anl.gov',NULL,NULL),
(45,'puttkamm.lock','Anthony','Puttkammer',NULL,'puttkamm@aps.anl.gov',NULL,NULL),
(46,'wiemer.lock','Greg','Wiemerslage',NULL,'wiemer@aps.anl.gov',NULL,NULL),
(47,'kknoerzer.lock','Kevin','Knoerzer',NULL,'kknoerzer@aps.anl.gov',NULL,NULL),
(48,'jacarter.lock','Jason','Carter',NULL,'jacarter',NULL,NULL),
(49,'adonnelly.lock','Aric','Donnelly',NULL,'adonnelly@aps.anl.gov',NULL,NULL),
(50,'hoytman.lock','John','Hoyt',NULL,'hoytman@aps.anl.gov',NULL,NULL),
(51,'suthar.lock','Kamlesh','Suthar',NULL,'suthar@aps.anl.gov',NULL,NULL),
(52,'dwalters.lock','Dean','Walters',NULL,'dwalters@aps.anl.gov',NULL,NULL),
(53,'clute.lock','Timothy','Clute',NULL,NULL,NULL,NULL),
(54,'gmm.lock','Greg','Markovich',NULL,'gmm@aps.anl.gov',NULL,NULL),
(55,'bderiy.lock','Boris','Deriy',NULL,'bderiy@aps.anl.gov',NULL,NULL),
(56,'gas.lock','Gary','Sprau',NULL,'gas@aps.anl.gov',NULL,NULL),
(57,'zconway.lock','Zachery','Conway',NULL,'zconway@anl.gov',NULL,NULL),
(58,'jtoeller.lock','Jeff','Toeller',NULL,'jtoeller@aps.anl.gov',NULL,NULL),
(59,'berenc.lock','Tim','Berenc',NULL,'berenc@aps.anl.gov',NULL,NULL),
(60,'jox.lock','Julie','Cross','Olmted','jox@anl.gov',NULL,NULL),
(61,'denharto.lock','Pat','Den Hartog',NULL,'denharto@aps.anl.gov',NULL,NULL),
(62,'erdmann.lock','Mark','Erdmann',NULL,'erdmann@aps.anl.gov',NULL,NULL),
(63,'bechtold.lock','Ralph','Bechtold','R','bechtold@aps.anl.gov',NULL,NULL),
(64,'gagliano.lock','Joseph','Gagliano',NULL,'gagliano@aps.anl.gov',NULL,NULL),
(65,'martens.lock','Mark','Martens',NULL,'martens@aps.anl.gov',NULL,NULL);
/*!40000 ALTER TABLE `user_info` ENABLE KEYS */;
UNLOCK TABLES;
