{% set name = "ComponentDB-API" %}
{% set version = "3.14.0.dev0" %}

package:
  name: "{{ name|lower }}"  
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1760dc88ceca99d9e45c1a7fd77f26203d68d94e2fcdf850245abc7dd6e30b1c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:  
  build:
    - pip
    - python    
  run:
    - python
    - python-dateutil
    - six
    - urllib3


test:
  imports:
    - CdbApiFactory

about:
  home: "https://github.com/AdvancedPhotonSource/ComponentDB"
  license: "Copyright (c) UChicago Argonne, LLC. All rights reserved."    
  summary: "Library Containing Component DB APIs"