{% set name = "ComponentDB-API" %}
{% set version = "3.15.2" %}

package:
  name: "{{ name|lower }}"  
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 33979ae849995e13f04c8f0fe8a795e0354e48eb8111743a29997783d86a2253

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:  
  build:
    - pip
    - python    
  run:
    - python
    - python-dateutil
    - six
    - urllib3
    - certifi

test:
  imports:
    - CdbApiFactory

about:
  home: "https://github.com/AdvancedPhotonSource/ComponentDB"
  license: "Copyright (c) UChicago Argonne, LLC. All rights reserved."    
  summary: "Library Containing Component DB APIs"
