{% set name = "ComponentDB-API" %}
{% set version = "3.16.2" %}

package:
  name: "{{ name|lower }}"  
  version: "{{ version }}"
 
source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps

requirements:  
  build:
    - python>=3.10
    - setuptools    
    - pip
  run:
    - python>=3.10
    - python-dateutil
    - six
    - urllib3
    - certifi

test:
  imports:
    - CdbApiFactory

about:
  home: "https://github.com/AdvancedPhotonSource/ComponentDB"
  license: "Copyright (c) UChicago Argonne, LLC. All rights reserved."    
  summary: "Library Containing Component DB APIs"
