#!/bin/sh
#
# cdb-mysqld	This shell script takes care of starting and stopping
#		the CDB MySQL (cdb-mysqld).
#
# chkconfig: - 64 36
# description:	CDB MySQL database server.
# processname: mysqld
### BEGIN INIT INFO
# Provides: cdb-mysqld
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Short-Description: start and stop CDB MySQL server
# Description: CDB MySQL database server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Set root to default if needed.
MY_DIR=`dirname $0` && cd $MY_DIR && MY_DIR=`pwd`
if [ -z "${CDB_ROOT_DIR}" ]; then
    CDB_ROOT_DIR=$MY_DIR/../..
fi

# Source environment file.
CDB_USER=`id -nu`
CDB_HOST=`hostname -s`
CDB_ENV_FILE=${CDB_ROOT_DIR}/setup.sh
if [ ! -f ${CDB_ENV_FILE} ]; then
    echo "Environment file ${CDB_ENV_FILE} does not exist." 
    exit 2
fi
. ${CDB_ENV_FILE} > /dev/null 

MYSQL_BIN_DIR=/usr/bin
if [ -f $CDB_SUPPORT_DIR/mysql/$CDB_HOST_ARCH/bin/mysqld_safe ]; then
    # Use our own mysqld binary if it exists
    MYSQL_ROOT_DIR=$CDB_SUPPORT_DIR/mysql/$CDB_HOST_ARCH
    MYSQL_SCRIPTS_DIR=$MYSQL_ROOT_DIR/scripts
    MYSQL_BIN_DIR=$MYSQL_ROOT_DIR/bin
fi
CDB_DAEMON=$MYSQL_BIN_DIR/mysqld_safe
CDB_DAEMON_NAME=mysqld
CDB_DAEMON_PORT=3306
CDB_DAEMON_RUN_DIR=${CDB_INSTALL_DIR}/var/run/${CDB_DAEMON_NAME}
CDB_DAEMON_DATA_DIR=${CDB_DATA_DIR}/mysql
CDB_DAEMON_LOG_DIR=${CDB_INSTALL_DIR}/var/log
CDB_DAEMON_PID_FILE=${CDB_DAEMON_RUN_DIR}/${CDB_DAEMON_NAME}.${CDB_HOST}.pid
CDB_DAEMON_LOCK_FILE=${CDB_DAEMON_RUN_DIR}/${CDB_DAEMON_NAME}.${CDB_HOST}.lock
CDB_DAEMON_SOCK_FILE=${CDB_DAEMON_RUN_DIR}/${CDB_DAEMON_NAME}.${CDB_HOST}.sock
CDB_DAEMON_LOG_FILE=${CDB_DAEMON_LOG_DIR}/${CDB_DAEMON_NAME}.${CDB_HOST}.log
CDB_DAEMON_CONFIG_FILE=${CDB_INSTALL_DIR}/etc/mysql.conf

START_TIMEOUT=120
STOP_TIMEOUT=60

# extract value of a MySQL option from config files
# Usage: get_mysql_option SECTION VARNAME DEFAULT
# result is returned in $result
# We use my_print_defaults which prints all options from multiple files,
# with the more specific ones later; hence take the last match.
get_mysql_option(){
    result=`$MYSQL_BIN_DIR/my_print_defaults --defaults-file=$CDB_DAEMON_CONFIG_FILE "$1" | sed -n "s/^--$2=//p" | tail -n 1`
    if [ -z "$result" ]; then
        # not found, use default
        result="$3"
    fi
}

get_mysql_option mysqld datadir ${CDB_DATA_DIR}
datadir="$result"
get_mysql_option mysqld socket ${CDB_DAEMON_SOCK_FILE}
socketfile="$result"
get_mysql_option mysqld_safe log-error ${CDB_DAEMON_LOG_FILE}
errlogfile="$result"
get_mysql_option mysqld_safe pid-file ${CDB_DAEMON_PID_FILE}
mypidfile="$result"


start(){
    [ -x $CDB_DAEMON ] || exit 5
    # check to see if it's already running
    CDB_DAEMON_RUNNING=0
    if [ -f "$mypidfile" ]; then
        CDB_DAEMON_PID=`cat "$mypidfile" 2>/dev/null`
        if [ -n "$CDB_DAEMON_PID" ] && [ -d "/proc/$CDB_DAEMON_PID" ] ; then
            CDB_DAEMON_RUNNING=1
        fi
    fi
    RESPONSE=`$MYSQL_BIN_DIR/mysqladmin --socket="$socketfile" --user=UNKNOWN_MYSQL_USER ping 2>&1`
    if [ $CDB_DAEMON_RUNNING = 1 ] && [ $? = 0 ]; then
        # already running, do nothing
        action $"Starting $CDB_DAEMON_NAME: " /bin/true
        ret=0
    elif [ $CDB_DAEMON_RUNNING = 1 ] && echo "$RESPONSE" | grep -q "Access denied for user"; then
        # already running, do nothing
        action $"Starting $CDB_DAEMON_NAME: " /bin/true
        ret=0
    else
    	# prepare for start
        mkdir -p `dirname $errlogfile`
        mkdir -p `dirname $mypidfile` 
	    touch "$errlogfile" 2>/dev/null
	    if [ $? -ne 0 ]; then
	        # failed to touch log file, probably insufficient permissions
	        action $"Starting $CDB_DAEMON_NAME: " /bin/false
	        return 4
	    fi
	    chown $CDB_USER "$errlogfile" 
	    chmod 0640 "$errlogfile"
	    [ -x /sbin/restorecon ] && /sbin/restorecon "$errlogfile"
	    if [ ! -d "$datadir/mysql" ] ; then
            # First, make sure $datadir is there with correct permissions
            if [ ! -e "$datadir" -a ! -h "$datadir" ]; then
                mkdir -p "$datadir" || exit 1
            fi
            chown $CDB_USER "$datadir"
            chmod 0755 "$datadir"
            [ -x /sbin/restorecon ] && /sbin/restorecon "$datadir"
            # Now create the database
            cd $MYSQL_ROOT_DIR
            action $"Initializing CDB MySQL database: " $MYSQL_SCRIPTS_DIR/mysql_install_db --datadir="$datadir" --user=$CDB_USER
            ret=$?
            chown -R $CDB_USER "$datadir"
            if [ $ret -ne 0 ] ; then
                return $ret
            fi
        fi
        chown $CDB_USER "$datadir"
        chmod 0755 "$datadir"
	    # Pass all the options determined above, to ensure consistent behavior.
	    # In many cases mysqld_safe would arrive at the same conclusions anyway
	    # but we need to be sure.  (An exception is that we don't force the
	    # log-error setting, since this script doesn't really depend on that,
	    # and some users might prefer to configure logging to syslog.)
	    # Note: set --basedir to prevent probes that might trigger SELinux
	    # alarms, per bug #547485
        if [ -S "$socketfile" ] ; then
            echo "Another CDB MySQL daemon already running with the same unix socket."
            action $"Starting $CDB_DAEMON_NAME: " /bin/false
            return 1
        fi

        # Debugging
	    #cmd="$CDB_DAEMON --defaults-file=$CDB_DAEMON_CONFIG_FILE --datadir=$datadir --socket=$socketfile --pid-file=$mypidfile --basedir=/usr --user=$CDB_USER" 
        #echo $cmd

        basedir=`dirname $MYSQL_BIN_DIR`
	    $CDB_DAEMON --defaults-file=$CDB_DAEMON_CONFIG_FILE \
            --datadir="$datadir" --socket="$socketfile" \
            --pid-file="$mypidfile" --basedir=$basedir --user=$CDB_USER \
            > /dev/null 2>&1 &
	    safe_pid=$!
	    # Spin for a maximum of N seconds waiting for the server to come up;
	    # exit the loop immediately if mysqld_safe process disappears.
	    # Rather than assuming we know a valid username, accept an "access
	    # denied" response as meaning the server is functioning.
	    ret=0
	    TIMEOUT="$START_TIMEOUT"
	    while [ $TIMEOUT -gt 0 ]; do
	        RESPONSE=`$MYSQL_BIN_DIR/mysqladmin --socket="$socketfile" --user=UNKNOWN_MYSQL_USER ping 2>&1`
	        mret=$?
	        if [ $mret -eq 0 ]; then
		        break
	        fi
	        # exit codes 1, 11 (EXIT_CANNOT_CONNECT_TO_SERVICE) are expected,
	        # anything else suggests a configuration error
	        if [ $mret -ne 1 -a $mret -ne 11 ]; then
		        echo "$RESPONSE"
		        echo "Cannot check for MySQL Daemon startup because of mysqladmin failure."
		        ret=1
		        break
	        fi
	        echo "$RESPONSE" | grep -q "Access denied for user" && break
	        if ! /bin/kill -0 $safe_pid 2>/dev/null; then
		        echo "MySQL Daemon failed to start."
		        ret=1
		        break
	        fi
	        sleep 1
	        let TIMEOUT=${TIMEOUT}-1
	    done
	    if [ $TIMEOUT -eq 0 ]; then
	        echo "Timeout error occurred trying to start MySQL Daemon."
	        ret=1
	    fi
	    if [ $ret -eq 0 ]; then
	        action $"Starting $CDB_DAEMON_NAME: " /bin/true
	        chmod o+r $mypidfile >/dev/null 2>&1
	        touch $CDB_DAEMON_LOCK_FILE
	    else
	        action $"Starting $CDB_DAEMON_NAME: " /bin/false
	    fi
    fi
    return $ret
}

stop() {
	if [ ! -f "$mypidfile" ]; then
	    # not running; per LSB standards this is "ok"
	    action $"Stopping $CDB_DAEMON_NAME: " /bin/true
	    return 0
	fi
	CDB_DAEMON_PID=`cat "$mypidfile" 2>/dev/null`
	if [ -n "$CDB_DAEMON_PID" ]; then
	    /bin/kill "$CDB_DAEMON_PID" >/dev/null 2>&1
	    ret=$?
	    if [ $ret -eq 0 ]; then
		    TIMEOUT="$STOP_TIMEOUT"
		    while [ $TIMEOUT -gt 0 ]; do
		        /bin/kill -0 "$CDB_DAEMON_PID" >/dev/null 2>&1 || break
		        sleep 1
		        let TIMEOUT=${TIMEOUT}-1
		    done
		    if [ $TIMEOUT -eq 0 ]; then
		        echo "Timeout error occurred trying to stop MySQL Daemon."
		        ret=1
		        action $"Stopping $CDB_DAEMON_NAME: " /bin/false
		    else
		        rm -f $CDB_DAEMON_LOCK_FILE
		        rm -f "$socketfile"
		        action $"Stopping $CDB_DAEMON_NAME: " /bin/true
		    fi
	    else
		    action $"Stopping $CDB_DAEMON_NAME: " /bin/false
	    fi
	else
	    # failed to read pidfile, probably insufficient permissions
	    action $"Stopping $CDB_DAEMON_NAME: " /bin/false
	    ret=4
	fi
	return $ret
}
 
restart() {
    stop
    start
}

condrestart() {
    [ -e $CDB_DAEMON_LOCK_FILE ] && restart || :
}


# See how we were called.
case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status -p "$mypidfile" $CDB_DAEMON_NAME
    ;;
    restart)
        restart
    ;;
    condrestart|try-restart)
        condrestart
    ;;
    reload)
        exit 3
    ;;
    force-reload)
        restart
    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac

exit $?
