#! /bin/sh
### BEGIN INIT INFO
# Provides:          glassfish
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Controls CDB GlassFish application server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Set root to default if needed.
MY_DIR=`dirname $0` && cd $MY_DIR && MY_DIR=`pwd`
if [ -z "${CDB_ROOT_DIR}" ]; then
    CDB_ROOT_DIR=$MY_DIR/../..
fi
        
# Source environment file.
CDB_USER=`id -nu`
CDB_HOST=`hostname -s`
CDB_ENV_FILE=${CDB_ROOT_DIR}/setup.sh
if [ ! -f ${CDB_ENV_FILE} ]; then
    echo "Environment file ${CDB_ENV_FILE} does not exist." 
    exit 2
fi
. ${CDB_ENV_FILE} > /dev/null

export AS_JAVA=$CDB_SUPPORT_DIR/java/$CDB_HOST_ARCH
GLASSFISH_DIR=$CDB_SUPPORT_DIR/glassfish/$CDB_HOST_ARCH
DERBY_DIR=$CDB_SUPPORT_DIR/glassfish/$CDB_HOST_ARCH/javadb/bin

CDB_DAEMON_NAME=glassfish
CDB_DAEMON_CONTROL_CMD=$GLASSFISH_DIR/bin/asadmin
CDB_DAEMON_START_ARGS="start-domain domain1"
CDB_DAEMON_STOP_ARGS="stop-domain domain1"
CDB_DAEMON_STATUS_CMDS="uptime list-domains list-applications list-jdbc-resources"

start() {
    echo -n $"Starting ${CDB_DAEMON_NAME}: "       
    # Check if we're a privileged user
    if [ `id -u` = 0 -a ${CDB_USER} != "root" ]; then
        su -m -c "${CDB_DAEMON_CONTROL_CMD} ${CDB_DAEMON_START_ARGS}" ${CDB_USER}
    else
        ${CDB_DAEMON_CONTROL_CMD} ${CDB_DAEMON_START_ARGS}
    fi
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success $"${CDB_DAEMON_NAME} startup" || failure $"${CDB_DAEMON_NAME} startup"
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping ${CDB_DAEMON_NAME}: "       
    # Check if we're a privileged user
    if [ `id -u` = 0 -a ${CDB_USER} != "root" ]; then
        su -m -c "${CDB_DAEMON_CONTROL_CMD} ${CDB_DAEMON_STOP_ARGS}" ${CDB_USER}
    else
        ${CDB_DAEMON_CONTROL_CMD} ${CDB_DAEMON_STOP_ARGS}
    fi
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success $"${CDB_DAEMON_NAME} shutdown" || failure $"${CDB_DAEMON_NAME} shutdown"
    echo
    return $RETVAL
}

status() {
    # Check if we're a privileged user
    if [ `id -u` = 0 -a ${CDB_USER} != "root" ]; then
        for cmd in ${CDB_DAEMON_STATUS_CMDS}; do
            su -m -c "${CDB_DAEMON_CONTROL_CMD} ${cmd}" ${CDB_USER}
        done
    else
        for cmd in ${CDB_DAEMON_STATUS_CMDS}; do
            ${CDB_DAEMON_CONTROL_CMD} ${cmd}
        done
    fi
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    status)
        status
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
esac


