LOCK TABLES `item_type` WRITE;
/*!40000 ALTER TABLE `item_type` DISABLE KEYS */;
INSERT INTO `item_type` VALUES
(1,'Building',NULL),
(2,'Area',NULL),
(3,'Room',NULL),
(4,'Table',NULL),
(5,'Cabinet',NULL),
(6,'Rack',NULL),
(7,'Shelf',NULL),
(8,'Vacuum Valve',NULL),
(9,'Vacuum Chamber',NULL),
(10,'BPM',NULL),
(11,'Absorber',NULL),
(12,'Assembly',NULL),
(13,'Vacuum Pump',NULL),
(14,'Gauge/Sensor - RGA',NULL),
(15,'Controller - Ion Pump',NULL),
(16,'Cable',NULL),
(17,'Controller - Vacuum Gauge',NULL),
(18,'Enclosure',NULL),
(19,'Card Cage',NULL),
(20,'Controller - Generic',NULL),
(21,'Controller - Gate Valve',NULL),
(22,'Controller - Heat tape',NULL),
(23,'Controller - PID',NULL),
(24,'Controller - Temperature',NULL),
(25,'Controller - Motor',NULL),
(26,'Controller - Power Supply',NULL),
(27,'Controller - PLC',NULL),
(28,'Controller - Water flow',NULL),
(29,'Controller - RGA',NULL),
(30,'Monitoring System',NULL),
(31,'Gauge/Sensor - strain',NULL),
(32,'Gauge/Sensor  - vacuum',NULL),
(33,'Gauge/Sensor  - thermocouple',NULL),
(34,'Gauge/Sensor  - RTD',NULL),
(35,'Gauge/Sensor  - pressure',NULL),
(36,'Gauge/Sensor - waterflow',NULL),
(37,'Motor',NULL),
(38,'Motor - Driver',NULL),
(39,'Motor - Position Monitor',NULL),
(40,'Motor - Limit Switch',NULL),
(41,'Patch Panel',NULL),
(42,'Adapter',NULL),
(43,'Module',NULL),
(44,'Blackbox',NULL),
(45,'ADC',NULL),
(46,'DAC',NULL),
(47,'Discrete I/O',NULL),
(48,'CPU',NULL),
(49,'FPGA',NULL),
(50,'Oscilloscope/DSA',NULL),
(51,'Counter',NULL),
(52,'Function Generator',NULL),
(53,'Frequency Synthesizer',NULL),
(54,'Voltmeter',NULL),
(55,'Power Supply',NULL),
(56,'Amplifier',NULL),
(57,'Multiplexor',NULL),
(58,'Interlock',NULL),
(59,'Readout/Display',NULL),
(60,'Controls Component',NULL),
(61,'Network',NULL),
(62,'Timing',NULL),
(63,'IOC',NULL),
(64,'Computer - Server/Workstation',NULL),
(65,'Video',NULL),
(66,'Interface Adapter',NULL),
(67,'Accelerator Component',NULL),
(68,'Girder',NULL),
(69,'Stand',NULL),
(70,'Transition Piece',NULL),
(71,'Heat Tape',NULL),
(72,'Flag',NULL),
(73,'Scraper',NULL),
(74,'Bellows',NULL),
(75,'Vacuum Flange',NULL),
(76,'Vacuum Seal',NULL),
(77,'Fastener',NULL),
(78,'Water line',NULL),
(79,'Water fitting',NULL),
(80,'Water seal',NULL),
(81,'Magnet Component',NULL),
(82,'Trim',NULL),
(83,'Dipole',NULL),
(84,'Quadrupole',NULL),
(85,'Sextupole',NULL),
(86,'PS Component',NULL),
(87,'Diagnostic Component',NULL),
(88,'Loss Monitor',NULL),
(89,'Current Monitor',NULL),
(90,'Screen',NULL),
(91,'Optics',NULL),
(92,'RF Component',NULL),
(93,'Cavity/accelerating structure',NULL),
(94,'Phase shifter',NULL),
(95,'Attenuator',NULL),
(96,'coupler',NULL),
(97,'Envelope detector',NULL),
(98,'Phase monitor/detector',NULL),
(99,'Klystron',NULL),
(100,'HVPS',NULL),
(101,'Splitter',NULL),
(102,'RF Source',NULL),
(103,'Circulator',NULL),
(104,'Beamline Component',NULL),
(105,'Insertion Device Component',NULL),
(106,'Plate',NULL),
(107,'CSBEND',NULL),
(108,'KQUAD',NULL),
(109,'KSEXT',NULL),
(110,'MONI',NULL),
(111,'VERTEX-POINT',NULL),
(112,'Computer - Laptop/Tablet',NULL),
(113,'High Voltage Pulser',NULL),
(114,'High Voltage Attenuator',NULL),
(115,'Plinth',NULL),
(116,'Flash Disk',NULL),
(117,'BPM Processor','Takes BPM signals, converts to X/Y/Sum'),
(118,'Instrumentation Component',NULL),
(119,'MARK',NULL),
(120,'Fan',NULL),
(121,'Fanout',NULL),
(122,'Data Logging System',NULL),
(123,'Measurement System',NULL),
(124,'Gateway/Protocol Converter',NULL),
(125,'Current Transformer',NULL),
(126,'Support',NULL),
(127,'Signal Converter',NULL);
/*!40000 ALTER TABLE `item_type` ENABLE KEYS */;
UNLOCK TABLES;
