LOCK TABLES `source` WRITE;
/*!40000 ALTER TABLE `source` DISABLE KEYS */;
INSERT INTO `source` VALUES
(1,'TBD',NULL),
(2,'VAT Valve',NULL),
(3,'Gamma Vacuum',NULL),
(4,'Ametek',NULL),
(5,'Televac',NULL),
(6,'APS/VAC',NULL),
(7,'APS/CTL',NULL),
(8,'APS/PSG',NULL),
(9,'APS/MED',NULL),
(10,'APS/RF',NULL);
/*!40000 ALTER TABLE `source` ENABLE KEYS */;
UNLOCK TABLES;
