LOCK TABLES `user_info` WRITE;
/*!40000 ALTER TABLE `user_info` DISABLE KEYS */;
INSERT INTO `user_info` VALUES
(1,'cdb','CDB','System Account',NULL,'cdb@aps.anl.gov',NULL,NULL),
(2,'bstill','Ben','Stillwell',NULL,'bstill@aps.anl.gov',NULL,NULL),
(3,'nda','Ned','Arnold',NULL,'nda@aps.anl.gov',NULL,NULL),
(4,'sveseli','Sinisa','Veseli',NULL,'sveseli@aps.anl.gov',NULL,NULL),
(5,'benes','Scott','Benes',NULL,'benes@aps.anl.gov',NULL,NULL),
(6,'nschwarz','Nicholas','Schwarz',NULL,'nschwarz@aps.anl.gov',NULL,NULL),
(7,'cease','Herman','Cease',NULL,'cease@aps.anl.gov',NULL,NULL),
(8,'carwar','John','Carwardine',NULL,'carwar@aps.anl.gov',NULL,NULL),
(9,'decker','Glenn','Decker',NULL,'decker@aps.anl.gov',NULL,NULL),
(10,'ngrossman','Nancy','Grossman',NULL,'ngrossman@aps.anl.gov',NULL,NULL),
(11,'cprokuski','Chuck','Prokuski',NULL,'cprokuski@aps.anl.gov',NULL,NULL),
(12,'jaski','Mark','Jaski',NULL,'jaski@aps.anl.gov',NULL,NULL),
(13,'juw','Ju','Wang',NULL,'juw@aps.anl.gov',NULL,NULL),
(14,'blill','Bob','Lill',NULL,'blill@aps.anl.gov',NULL,NULL),
(15,'horan','Doug','Horan',NULL,'horan@aps.anl.gov',NULL,NULL),
(16,'fornek','Tom','Fornek',NULL,'fornek@aps.anl.gov',NULL,NULL),
(17,'rif','Richard','Farnsworth',NULL,'rif@aps.anl.gov',NULL,NULL),
(18,'frl','Frank','Lenkszus',NULL,'frl@aps.anl.gov',NULL,NULL),
(19,'preissner','Curt','Preissner',NULL,'preissner@aps.anl.gov',NULL,NULL),
(20,'lhm','Leonard','Morrison',NULL,'lhm@aps.anl.gov',NULL,NULL),
(21,'jieliu','Jie','Liu',NULL,'jieliu@aps.anl.gov',NULL,NULL),
(22,'doose','Charles','Doose',NULL,'doose@aps.anl.gov',NULL,NULL),
(23,'tfors','Tom','Fors',NULL,'tfors@aps.anl.gov',NULL,NULL),
(24,'bran','Bran','Brajuskovic',NULL,'bran@aps.anl.gov',NULL,NULL),
(25,'jzientek','John','Zientek',NULL,'jzientek@aps.anl.gov',NULL,NULL),
(26,'djarosz','Dariusz','Jarosz','Piotr','djarosz@aps.anl.gov',NULL,NULL),
(27,'mwhite','Marion','White',NULL,'mwhite@aps.anl.gov',NULL,NULL),
(28,'brianr','Brian','Rusthoven',NULL,'brianr@aps.anl.gov',NULL,NULL),
(29,'shoaf','Steve','Shoaf',NULL,'shoaf@aps.anl.gov',NULL,NULL),
(30,'hbui','Hanh','Bui',NULL,'hbui@aps.anl.gov',NULL,NULL),
(31,'sereno','Nick','Sereno',NULL,'sereno@aps.anl.ogv',NULL,NULL),
(32,'xusf','Shifu','Xu',NULL,'xusf@aps.anl.gov',NULL,NULL),
(33,'afp','Tony','Pietryla',NULL,'afp',NULL,NULL),
(34,'rblake','Ron','Blake',NULL,'rblake@aps.anl.gov',NULL,NULL),
(35,'dejus','Roger','Dejus',NULL,'dejus@aps.anl.gov',NULL,NULL),
(36,'collins','Jeff','Collins',NULL,'collins@aps.anl.gov',NULL,NULL),
(37,'keane','Rob','Keane',NULL,'keane@aps.anl.gov',NULL,NULL),
(38,'jzxu','Joe','Xu',NULL,'jzxu@aps.anl.gov',NULL,NULL),
(39,'jnudell','Jeremy','Nudell',NULL,'jnudell@aps.anl.gov',NULL,NULL),
(40,'borland','Michael','Borland',NULL,'borland@aps.anl.gov',NULL,NULL),
(41,'soprondek','Samuel','Oprondek',NULL,'soprondek@aps.anl.gov',NULL,NULL),
(42,'hanuska','Steve','Hanuska',NULL,'hanuska@aps.anl.gov',NULL,NULL),
(43,'nda1','Ned','Arnold','Local','nda@aps.anl.gov',NULL,NULL),
(44,'jabraham','Josh','Abraham',NULL,'jabraham@anl.gov',NULL,NULL),
(45,'puttkamm','Anthony','Puttkammer',NULL,'puttkamm@aps.anl.gov',NULL,NULL),
(46,'wiemer','Greg','Wiemerslage',NULL,'wiemer@aps.anl.gov',NULL,NULL),
(47,'kknoerzer','Kevin','Knoerzer',NULL,'kknoerzer@aps.anl.gov',NULL,NULL),
(48,'jacarter','Jason','Carter',NULL,'jacarter',NULL,NULL),
(49,'adonnelly','Aric','Donnelly',NULL,'adonnelly@aps.anl.gov',NULL,NULL),
(50,'hoytman','John','Hoyt',NULL,'hoytman@aps.anl.gov',NULL,NULL),
(51,'suthar','Kamlesh','Suthar',NULL,'suthar@aps.anl.gov',NULL,NULL),
(52,'dwalters','Dean','Walters',NULL,'dwalters@aps.anl.gov',NULL,NULL);
/*!40000 ALTER TABLE `user_info` ENABLE KEYS */;
UNLOCK TABLES;
