LOCK TABLES `source` WRITE;
/*!40000 ALTER TABLE `source` DISABLE KEYS */;
INSERT INTO `source` VALUES
(1,'TBD',NULL,NULL,NULL),
(2,'VAT Valve','','','www.vatvalve.com'),
(3,'Gamma Vacuum','','','www.gammavacuum.com'),
(4,'Ametek',NULL,NULL,NULL),
(5,'Televac','','','www.televac.com'),
(6,'APS/VAC',NULL,NULL,NULL),
(7,'APS/CTL',NULL,NULL,NULL),
(8,'APS/PSG',NULL,NULL,NULL),
(9,'APS/MED',NULL,NULL,NULL),
(10,'APS/RF',NULL,NULL,NULL),
(11,'FID GmbH','','','http://www.fidtechnology.com/'),
(12,'ATF',NULL,NULL,NULL),
(13,'Keysight (Agilent)','','','www.keysight.com'),
(14,'Moose Hill Enterprises',NULL,NULL,NULL),
(15,'Amazon','','','www.amazon.com'),
(16,'Schroff','','','http://www.pentairprotect.co.uk/'),
(17,'CommAgility','','','http://www.commagility.com'),
(18,'N.A.T.','Networking, Automation and Technology Co.','','http://www.nateurope.com/'),
(19,'Wiener, Plien & Baus,  GmbH ','','','http://www.wiener-us.com/'),
(20,'Concurrent Technologies','','','http://www.gocct.com/'),
(21,'Instrumentation Technologies (I-Tech)','','','www.i-tech.si'),
(22,'Micro-Research Finland Oy (MRF)','','','http://www.mrf.fi/'),
(23,'Opal Kelly','FPGA Boards','','http://www.opalkelly.com'),
(24,'Midwest Vacuum','Vacuum Components Vendor','Hans Luedi, 630-323-5399, hluedi@midwestvacuum.com','http://www.midwestvacuum.com/Home.9.0.html'),
(25,'Vacuum One','Vacumm Components Vendor','Scott Dix, 408-510-2459, info@vacuumone.com','http://www.vacuumone.com/'),
(26,'VACOM','Vacuum Components Vendor','Michael Pick, +49 3641 4275-33, michael.pick@vacom.de','http://www.vacom.de/en/'),
(27,'Edwards','Vacuum products manufacturer','','https://www.edwardsvacuum.com'),
(28,'Pulse Research Lab','','sales@pulseresearchlab.com','www.pulseresearchlab.com'),
(29,'Danfysik','','','http://www.danfysik.com/'),
(31,'Moxa','','','http://www.moxa.com/'),
(32,'Danisense','','','www.danisense.com'),
(33,'APS/DIAG','','',''),
(34,'Dukane Precast','','','www.dukaneprecast.com'),
(35,'American Grinding','','',''),
(36,'BiRa Systems','','Pawel Kowalski [pawel@bira.com]','http://www.bira.com'),
(37,'Krohn-Hite','','','http://www.krohn-hite.com/'),
(38,'Vishay','','','http://vpgsensors.com/'),
(39,'Blackhawk','Blackhawkâ„¢ is a business unit of EWA/EWA Technologies, Inc.','','http://www.blackhawk-dsp.com/'),
(40,'Kooltronic, Inc.','','Bruce Kreeley','http://www.kooltronic.com/'),
(41,'CAEN Technologies, Inc.','','erik@caentechnologies.com','http://www.caenels.com/');
/*!40000 ALTER TABLE `source` ENABLE KEYS */;
UNLOCK TABLES;
