LOCK TABLES `item_element_relationship` WRITE;
/*!40000 ALTER TABLE `item_element_relationship` DISABLE KEYS */;
INSERT INTO `item_element_relationship` VALUES
(1,41,NULL,NULL,139,NULL,NULL,NULL,1,NULL,'',NULL,NULL,NULL),
(4,60,NULL,NULL,137,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL),
(5,143,NULL,NULL,161,NULL,NULL,NULL,5,NULL,NULL,NULL,NULL,NULL),
(6,144,NULL,NULL,162,NULL,NULL,NULL,4,NULL,NULL,NULL,'PRI',NULL),
(7,146,NULL,NULL,162,NULL,NULL,NULL,4,NULL,NULL,NULL,'PRI',NULL);
/*!40000 ALTER TABLE `item_element_relationship` ENABLE KEYS */;
UNLOCK TABLES;
