LOCK TABLES `system_log` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `system_log` DISABLE KEYS */;
INSERT INTO `system_log` VALUES
(1,3);
/*!40000 ALTER TABLE `system_log` ENABLE KEYS */;
UNLOCK TABLES;
