LOCK TABLES `connector_type` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `connector_type` DISABLE KEYS */;
INSERT INTO `connector_type` VALUES
(1,'RJ-45','');
/*!40000 ALTER TABLE `connector_type` ENABLE KEYS */;
UNLOCK TABLES;
