LOCK TABLES `allowed_entity_type` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `allowed_entity_type` DISABLE KEYS */;
/*!40000 ALTER TABLE `allowed_entity_type` ENABLE KEYS */;
UNLOCK TABLES;
