LOCK TABLES `log_topic` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `log_topic` DISABLE KEYS */;
INSERT INTO `log_topic` VALUES
(1,'General',NULL);
/*!40000 ALTER TABLE `log_topic` ENABLE KEYS */;
UNLOCK TABLES;
