LOCK TABLES `item_element_relationship` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `item_element_relationship` DISABLE KEYS */;
INSERT INTO `item_element_relationship` VALUES
(1,41,NULL,NULL,139,NULL,NULL,1,NULL,'',NULL,NULL,NULL),
(2,144,NULL,NULL,148,NULL,1.00,4,NULL,NULL,NULL,NULL,NULL),
(3,146,NULL,NULL,148,NULL,2.00,4,NULL,NULL,NULL,NULL,NULL),
(4,60,NULL,NULL,137,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL),
(5,143,NULL,NULL,161,NULL,NULL,5,NULL,NULL,NULL,NULL,NULL);
/*!40000 ALTER TABLE `item_element_relationship` ENABLE KEYS */;
UNLOCK TABLES;
