LOCK TABLES `item_element_log` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `item_element_log` DISABLE KEYS */;
/*!40000 ALTER TABLE `item_element_log` ENABLE KEYS */;
UNLOCK TABLES;
