LOCK TABLES `user_group_setting` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `user_group_setting` DISABLE KEYS */;
/*!40000 ALTER TABLE `user_group_setting` ENABLE KEYS */;
UNLOCK TABLES;
