LOCK TABLES `source` WRITE;
/*!40000 ALTER TABLE `source` DISABLE KEYS */;
INSERT INTO `source` VALUES
(1,'TBD',NULL,NULL,NULL),
(2,'VAT Valve',NULL,NULL,'www.vatvalve.com'),
(3,'Gamma Vacuum',NULL,NULL,'www.gammavacuum.com'),
(4,'Ametek',NULL,NULL,NULL),
(5,'Televac',NULL,NULL,'www.televac.com'),
(6,'APS/VAC',NULL,NULL,NULL),
(7,'APS/CTL',NULL,NULL,NULL),
(8,'APS/PSG',NULL,NULL,NULL),
(9,'APS/MED',NULL,NULL,NULL),
(10,'APS/RF',NULL,NULL,NULL),
(11,'FID GmbH',NULL,NULL,'http://www.fidtechnology.com/'),
(12,'ATF',NULL,NULL,NULL),
(13,'Keysight (Agilent)',NULL,NULL,'www.keysight.com'),
(14,'Moose Hill Enterprises',NULL,NULL,NULL),
(15,'Amazon',NULL,NULL,'www.amazon.com'),
(16,'Schroff',NULL,NULL,'http://www.pentairprotect.co.uk/'),
(17,'CommAgility',NULL,NULL,'http://www.commagility.com'),
(18,'N.A.T.','Networking, Automation and Technology Co.',NULL,'http://www.nateurope.com/'),
(19,'Wiener, Plien & Baus,  GmbH ',NULL,NULL,'http://www.wiener-us.com/'),
(20,'Concurrent Technologies',NULL,NULL,'http://www.gocct.com/'),
(21,'Instrumentation Technologies (I-Tech)',NULL,NULL,'www.i-tech.si'),
(22,'Micro-Research Finland Oy (MRF)',NULL,NULL,'http://www.mrf.fi/'),
(23,'Opal Kelly','FPGA Boards',NULL,'http://www.opalkelly.com'),
(24,'Midwest Vacuum','Vacuum Components Vendor',NULL,'http://www.midwestvacuum.com/Home.9.0.html'),
(25,'Vacuum One','Vacumm Components Vendor',NULL,'http://www.vacuumone.com/'),
(26,'VACOM','Vacuum Components Vendor',NULL,'http://www.vacom.de/en/'),
(27,'Edwards','Vacuum products manufacturer',NULL,'https://www.edwardsvacuum.com'),
(28,'Pulse Research Lab',NULL,NULL,'www.pulseresearchlab.com'),
(29,'Danfysik',NULL,NULL,'http://www.danfysik.com/'),
(30,'Moxa',NULL,NULL,'http://www.moxa.com/'),
(31,'Danisense',NULL,NULL,'www.danisense.com'),
(32,'APS/DIAG',NULL,NULL,NULL),
(33,'Dukane Precast',NULL,NULL,'www.dukaneprecast.com'),
(34,'American Grinding',NULL,NULL,NULL),
(35,'BiRa Systems',NULL,NULL,'http://www.bira.com'),
(36,'Krohn-Hite',NULL,NULL,'http://www.krohn-hite.com/'),
(37,'Vishay',NULL,NULL,'http://vpgsensors.com/'),
(38,'Blackhawk','Blackhawk is a business unit of EWA/EWA Technologies, Inc.',NULL,'http://www.blackhawk-dsp.com/'),
(39,'Kooltronic, Inc.',NULL,NULL,'http://www.kooltronic.com/'),
(40,'CAEN Technologies, Inc.',NULL,NULL,'http://www.caenels.com/'),
(41,'DIAL MACHINE, INC','PRECISION MACHINING, BIG PARTS',NULL,'http://www.dialmachine.com/'),
(42,'Emerson',NULL,NULL,NULL),
(43,'Arrow',NULL,NULL,NULL),
(44,'FMB-BERLIN','ACCELERATOR COMPONENT VENDOR',NULL,'http://fmb-berlin.de/en'),
(45,'ROBINSON METAL INC','Precision Machining, Assembly and UHV Welding',NULL,'www.robinsonmetal.com'),
(46,'HiTech Mfg.',NULL,NULL,NULL),
(47,'Atlas',NULL,NULL,NULL),
(48,'saes-group','ACCELERATOR COMPONENT VENDOR',NULL,'https://www.saesgetters.com/'),
(49,'Tecknit Shielding Systems inc.',NULL,NULL,NULL),
(50,'Barber-Nichols',NULL,NULL,NULL),
(51,'Johnson Controls',NULL,NULL,NULL),
(52,'Oxford',NULL,NULL,NULL);
/*!40000 ALTER TABLE `source` ENABLE KEYS */;
UNLOCK TABLES;
