LOCK TABLES `setting_type` WRITE;
/*!40000 ALTER TABLE `setting_type` DISABLE KEYS */;
INSERT INTO `setting_type` VALUES
(4,'AllowedPropertyValue.List.Display.Description','Display allowed property value description.','false'),
(5,'AllowedPropertyValue.List.Display.Id','Display allowed property value id.','false'),
(6,'AllowedPropertyValue.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(7,'AllowedPropertyValue.List.Display.SortOrder','Display allowed property value sort order.','true'),
(8,'AllowedPropertyValue.List.Display.Units','Display allowed property value units.','true'),
(9,'AllowedPropertyValue.List.FilterBy.Description','Filter for allowed property value description.',NULL),
(10,'AllowedPropertyValue.List.FilterBy.SortOrder','Filter for allowed property value class sort order.',NULL),
(11,'AllowedPropertyValue.List.FilterBy.Units','Filter for allowed property value units.',NULL),
(12,'AllowedPropertyValue.List.FilterBy.Value','Filter for allowed property value.',NULL),
(13,'AssemblyComponent.List.Display.Description','Display assembly component description.','true'),
(14,'AssemblyComponent.List.Display.FlatTableView','Display flat table view for assembly component list.','false'),
(15,'AssemblyComponent.List.Display.Id','Display assembly component id.','false'),
(16,'AssemblyComponent.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(17,'AssemblyComponent.List.Display.SortOrder','Display assembly component sort order.','true'),
(18,'AssemblyComponent.List.FilterBy.Description','Filter for assembly components by description.',NULL),
(19,'AssemblyComponent.List.FilterBy.Name','Filter for assembly components by name.',NULL),
(20,'AssemblyComponent.List.FilterBy.SortOrder','Filter for assembly components by sort order.',NULL),
(21,'Component.List.AutoLoad.FilterBy.Properties','Automatically load component list with display properties for filtering.','true'),
(22,'Component.List.Display.Category','Display component type category.','true'),
(23,'Component.List.Display.CreatedByUser','Display created by username.','false'),
(24,'Component.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(25,'Component.List.Display.Description','Display component description.','true'),
(26,'Component.List.Display.Id','Display component id.','false'),
(27,'Component.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(28,'Component.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(29,'Component.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(30,'Component.List.Display.ModelNumber','Display component model number.','true'),
(31,'Component.List.Display.OwnerUser','Display owner username.','true'),
(32,'Component.List.Display.OwnerGroup','Display owner group name.','true'),
(33,'Component.List.Display.PropertyTypeId1','Display property value for property type id #1.','72'),
(34,'Component.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(35,'Component.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(36,'Component.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(37,'Component.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(38,'Component.List.Display.Sources','Display component sources.','true'),
(39,'Component.List.Display.Type','Display component type.','true'),
(40,'Component.List.FilterBy.Category','Filter for components by type category.',NULL),
(41,'Component.List.FilterBy.CreatedByUser','Filter for components that were created by username.',NULL),
(42,'Component.List.FilterBy.CreatedOnDateTime','Filter for components that were created on date/time.',NULL),
(43,'Component.List.FilterBy.Description','Filter for components by description.',NULL),
(44,'Component.List.FilterBy.LastModifiedByUser','Filter for components that were last modified by username.',NULL),
(45,'Component.List.FilterBy.LastModifiedOnDateTime','Filter for components that were last modified on date/time.',NULL),
(46,'Component.List.FilterBy.ModelNumber','Filter for component model number.',NULL),
(47,'Component.List.FilterBy.PropertyValue1','Filter for property value with displayed property type id #1.',''),
(48,'Component.List.FilterBy.PropertyValue2','Filter for property value with displayed property type id #2.',''),
(49,'Component.List.FilterBy.PropertyValue3','Filter for property value with displayed property type id #3.',''),
(50,'Component.List.FilterBy.PropertyValue4','Filter for property value with displayed property type id #4.',''),
(51,'Component.List.FilterBy.PropertyValue5','Filter for property value with displayed property type id #5.',''),
(52,'Component.List.FilterBy.Name','Filter for components by name.',NULL),
(53,'Component.List.FilterBy.OwnerUser','Filter for components by owner username.',NULL),
(54,'Component.List.FilterBy.OwnerGroup','Filter for components by owner group name.',NULL),
(55,'Component.List.FilterBy.Sources','Filter for components by sources.',NULL),
(56,'Component.List.FilterBy.Type','Filter for components by type.',NULL),
(57,'Component.Help.ListPage.Display.Fragment', 'Display Help guide to the user on the main list page of the Component entity.', 'true'),
(58,'ComponentInstance.List.Display.CreatedByUser','Display created by username.','false'),
(59,'ComponentInstance.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(60,'ComponentInstance.List.Display.Description','Display component instance description.','true'),
(61,'ComponentInstance.List.Display.Id','Display component instance id.','false'),
(62,'ComponentInstance.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(63,'ComponentInstance.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(64,'ComponentInstance.List.Display.LocationDetails','Display component instance location details.','false'),
(65,'ComponentInstance.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(66,'ComponentInstance.List.Display.OwnerUser','Display owner username.','true'),
(67,'ComponentInstance.List.Display.OwnerGroup','Display owner group name.','true'),
(68,'ComponentInstance.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(69,'ComponentInstance.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(70,'ComponentInstance.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(71,'ComponentInstance.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(72,'ComponentInstance.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(73,'ComponentInstance.List.Display.QrId','Display component instance QR id.','true'),
(74,'ComponentInstance.List.Display.SerialNumber','Display component instance serial number.','false'),
(75,'ComponentInstance.List.FilterBy.Component','Filter for component instance component.',NULL),
(76,'ComponentInstance.List.FilterBy.CreatedByUser','Filter for components that were created by username.',NULL),
(77,'ComponentInstance.List.FilterBy.CreatedOnDateTime','Filter for components that were created on date/time.',NULL),
(78,'ComponentInstance.List.FilterBy.Description','Filter for components by description.',NULL),
(79,'ComponentInstance.List.FilterBy.LastModifiedByUser','Filter for components that were last modified by username.',NULL),
(80,'ComponentInstance.List.FilterBy.LastModifiedOnDateTime','Filter for components that were last modified on date/time.',NULL),
(81,'ComponentInstance.List.FilterBy.Location','Filter for component instance location.',NULL),
(82,'ComponentInstance.List.FilterBy.LocationDetails','Filter for component instance location details.',NULL),
(83,'ComponentInstance.List.FilterBy.OwnerUser','Filter for component instances by owner username.',NULL),
(84,'ComponentInstance.List.FilterBy.OwnerGroup','Filter for component instances by owner group name.',NULL),
(85,'ComponentInstance.List.FilterBy.PropertyValue1','Filter for property value with displayed property type id #1.',''),
(86,'ComponentInstance.List.FilterBy.PropertyValue2','Filter for property value with displayed property type id #2.',''),
(87,'ComponentInstance.List.FilterBy.PropertyValue3','Filter for property value with displayed property type id #3.',''),
(88,'ComponentInstance.List.FilterBy.PropertyValue4','Filter for property value with displayed property type id #4.',''),
(89,'ComponentInstance.List.FilterBy.PropertyValue5','Filter for property value with displayed property type id #5.',''),
(90,'ComponentInstance.List.FilterBy.QrId','Filter for component instance QR id.',NULL),
(91,'ComponentInstance.List.FilterBy.SerialNumber','Filter for component instance serial number.',NULL),
(92,'ComponentInstance.List.FilterBy.Tag','Filter for component instance tag.',NULL),
(93,'ComponentInstance.Help.ListPage.Display.Fragment', 'Display Help guide to the user on the main list page of the Component Instance entity.', 'true'),
(94,'ComponentInstanceLocationHistory.List.Display.EnteredOnDateTime','Display location entered on date/time.','true'),
(95,'ComponentInstanceLocationHistory.List.Display.EnteredByUser','Display location entered by user.','true'),
(96,'ComponentInstanceLocationHistory.List.Display.Id','Display entry id.','false'),
(97,'ComponentInstanceLocationHistory.List.Display.Location','Display Location name','true'),
(98,'ComponentInstanceLocationHistory.List.Display.LocationDetails','Display location details.','true'),
(99,'ComponentInstanceLocationHistory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(100,'ComponentInstanceLocationHistory.List.FilterBy.EnteredOnDateTime','Filter for location entered on date/time.',NULL),
(101,'ComponentInstanceLocationHistory.List.FilterBy.EnteredByUser','Filter for location entered by user.',NULL),
(102,'ComponentInstanceLocationHistory.List.FilterBy.Location','Filter for location name.',NULL),
(103,'ComponentInstanceLocationHistory.List.FilterBy.LocationDetails','Filter location details.',NULL),
(104,'ComponentSource.List.Display.ContactInfo','Display component source contact infpo.','false'),
(105,'ComponentSource.List.Display.Cost','Display component cost.','true'),
(106,'ComponentSource.List.Display.Description','Display component source description.','true'),
(107,'ComponentSource.List.Display.Id','Display component source id.','false'),
(108,'ComponentSource.List.Display.IsManufacturer','Display component source manufacturer designation.','true'),
(109,'ComponentSource.List.Display.IsVendor','Display component source vendor designation.','true'),
(110,'ComponentSource.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(111,'ComponentSource.List.Display.PartNumber','Display component part number.','true'),
(112,'ComponentSource.List.Display.Url','Display component source URL.','false'),
(113,'ComponentSource.List.FilterBy.ContactInfo','Filter for component sources by contact info.',NULL),
(114,'ComponentSource.List.FilterBy.Cost','Filter for component sources by cost.',NULL),
(115,'ComponentSource.List.FilterBy.Description','Filter for component sources by description.',NULL),
(116,'ComponentSource.List.FilterBy.IsManufacturer','Filter for component sources by manufacturer designation.',NULL),
(117,'ComponentSource.List.FilterBy.IsVendor','Filter for component sources by vendor designation.',NULL),
(118,'ComponentSource.List.FilterBy.PartNumber','Filter for component sources by part number.',NULL),
(119,'ComponentSource.List.FilterBy.SourceName','Filter for component sources by name.',NULL),
(120,'ComponentSource.List.FilterBy.Url','Filter for component sources by URL.',NULL),
(121,'ComponentType.List.Display.Category','Display component type category.','true'),
(122,'ComponentType.List.Display.Description','Display component type description.','true'),
(123,'ComponentType.List.Display.Id','Display component type id.','false'),
(124,'ComponentType.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(125,'ComponentType.List.FilterBy.Category','Filter for component type category.',NULL),
(126,'ComponentType.List.FilterBy.Description','Filter for component type description.',NULL),
(127,'ComponentType.List.FilterBy.Name','Filter for component type name.',NULL),
(128,'ComponentTypeCategory.List.Display.Description','Display component type category description.','true'),
(129,'ComponentTypeCategory.List.Display.Id','Display component type category id.','false'),
(130,'ComponentTypeCategory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(131,'ComponentTypeCategory.List.FilterBy.Description','Filter for component type category description.',NULL),
(132,'ComponentTypeCategory.List.FilterBy.Name','Filter for component type category name.',NULL),
(133,'ComponentTypePropertyType.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(134,'ComponentTypePropertyType.List.Display.Id','Display component type property type id.','false'),
(135,'ComponentTypePropertyType.List.FilterBy.PropertyTypeName','Filter for component type property type name.',NULL),
(136,'Design.List.Display.CreatedByUser','Display created by username.','false'),
(137,'Design.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(138,'Design.List.Display.Description','Display design description.','true'),
(139,'Design.List.Display.Id','Display design id.','false'),
(140,'Design.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(141,'Design.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(142,'Design.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(143,'Design.List.Display.OwnerUser','Display owner username.','true'),
(144,'Design.List.Display.OwnerGroup','Display owner group name.','true'),
(145,'Design.List.FilterBy.CreatedByUser','Filter for designs that were created by username.',NULL),
(146,'Design.List.FilterBy.CreatedOnDateTime','Filter for designs that were created on date/time.',NULL),
(147,'Design.List.FilterBy.Description','Filter for designs by description.',NULL),
(148,'Design.List.FilterBy.LastModifiedByUser','Filter for designs that were last modified by username.',NULL),
(149,'Design.List.FilterBy.LastModifiedOnDateTime','Filter for designs that were last modified on date/time.',NULL),
(150,'Design.List.FilterBy.Name','Filter for designs by name.',NULL),
(151,'Design.List.FilterBy.OwnerUser','Filter for designs by owner username.',NULL),
(152,'Design.List.FilterBy.OwnerGroup','Filter for designs by owner group name.',NULL),
(153,'Design.Member.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(154,'Design.Member.List.Display.Id','Display design id.','false'),
(155,'Design.Member.List.Display.Description','Display design description.','true'),
(156,'Design.Member.List.Display.OwnerUser','Display owner username.','true'),
(157,'Design.Member.List.Display.OwnerGroup','Display owner group name.','true'),
(158,'Design.Member.List.Display.CreatedByUser','Filter for designs that were created by username.','false'),
(159,'Design.Member.List.Display.CreatedOnDateTime','Filter for designs that were created on date/time.','false'),
(160,'Design.Member.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(161,'Design.Member.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(162,'Design.Help.ListPage.Display.Fragment', 'Display Help guide to the user on the main list page of the component entity.', 'true'),
(163,'DesignElement.List.Display.ChildDesign','Display child design.','true'),
(164,'DesignElement.List.Display.Component','Display component.','true'),
(165,'DesignElement.List.Display.ComponentType','Display component type.','false'),
(166,'DesignElement.List.Display.CreatedByUser','Display created by username.','false'),
(167,'DesignElement.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(168,'DesignElement.List.Display.Description','Display design element description.','false'),
(169,'DesignElement.List.Display.FlatTableView','Display flat table view for design element list.','false'),
(170,'DesignElement.List.Display.Id','Display design element id.','false'),
(171,'DesignElement.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(172,'DesignElement.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(173,'DesignElement.List.Display.Location','Display location.','true'),
(174,'DesignElement.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(175,'DesignElement.List.Display.OwnerUser','Display owner username.','true'),
(176,'DesignElement.List.Display.OwnerGroup','Display owner group name.','true'),
(177,'DesignElement.List.Display.SortOrder','Display design element sort order.','true'),
(178,'DesignElement.List.FilterBy.ChildDesign','Filter for child design.',NULL),
(179,'DesignElement.List.FilterBy.Component','Filter for component.',NULL),
(180,'DesignElement.List.FilterBy.ComponentType','Filter for component type.',NULL),
(181,'DesignElement.List.FilterBy.CreatedByUser','Filter for design elements that were created by username.',NULL),
(182,'DesignElement.List.FilterBy.CreatedOnDateTime','Filter for design elements that were created on date/time.',NULL),
(183,'DesignElement.List.FilterBy.Description','Filter for design elements by description.',NULL),
(184,'DesignElement.List.FilterBy.LastModifiedByUser','Filter for design elements that were last modified by username.',NULL),
(185,'DesignElement.List.FilterBy.LastModifiedOnDateTime','Filter for design elements that were last modified on date/time.',NULL),
(186,'DesignElement.List.FilterBy.Location','Filter for component.',NULL),
(187,'DesignElement.List.FilterBy.Name','Filter for design elements by name.',NULL),
(188,'DesignElement.List.FilterBy.OwnerUser','Filter for design elements by owner username.',NULL),
(189,'DesignElement.List.FilterBy.OwnerGroup','Filter for design elements by owner group name.',NULL),
(190,'DesignElement.List.FilterBy.SortOrder','Filter for design elements by sort order.',NULL),
(191,'DesignLink.List.Display.Description','Display design link description.','false'),
(192,'DesignLink.List.Display.Id','Display design link id.','false'),
(193,'DesignLink.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(194,'DesignLink.List.Display.Tag','Display design link tag.','true'),
(195,'Location.List.Display.Description','Display location description.','true'),
(196,'Location.List.Display.FlatTableView','Display flat table view for location list.','false'),
(197,'Location.List.Display.Id','Display location id.','false'),
(198,'Location.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(199,'Location.List.Display.Parent','Display location parent.','true'),
(200,'Location.List.Display.Type','Display location type.','true'),
(201,'Location.List.FilterBy.Description','Filter for location type description.',NULL),
(202,'Location.List.FilterBy.Name','Filter for location type name.',NULL),
(203,'Location.List.FilterBy.Parent','Filter for location parent.',NULL),
(204,'Location.List.FilterBy.Type','Filter for location type.',NULL),
(205,'LocationType.List.Display.Description','Display location type description.','true'),
(206,'LocationType.List.Display.Id','Display location type id.','false'),
(207,'LocationType.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(208,'LocationType.List.FilterBy.Description','Filter for location type description.',NULL),
(209,'LocationType.List.FilterBy.Name','Filter for location type name.',NULL),
(210,'Log.List.Display.Attachments','Display log entry attachments.','true'),
(211,'Log.List.Display.EnteredOnDateTime','Display log entry entered on date/time.','true'),
(212,'Log.List.Display.EnteredByUser','Display log entry entered by user.','true'),
(213,'Log.List.Display.Id','Display log entry id.','false'),
(214,'Log.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(215,'Log.List.Display.Topic','Display log topic.','false'),
(216,'Log.List.FilterBy.EnteredOnDateTime','Filter for log entry entered on date/time.',NULL),
(217,'Log.List.FilterBy.EnteredByUser','Filter for log entry entered by user.',NULL),
(218,'Log.List.FilterBy.Text','Filter for log entry text.',NULL),
(219,'Log.List.FilterBy.Topic','Filter for log topic.',NULL),
(220,'PropertyType.List.Display.Category','Display property type category.','true'),
(221,'PropertyType.List.Display.DefaultUnits','Display property type default units.','false'),
(222,'PropertyType.List.Display.DefaultValue','Display property type default value.','false'),
(223,'PropertyType.List.Display.Description','Display property type description.','true'),
(224,'PropertyType.List.Display.Handler','Display property type class handler.','true'),
(225,'PropertyType.List.Display.Id','Display property type id.','false'),
(226,'PropertyType.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(227,'PropertyType.List.FilterBy.Category','Filter for property type category.',NULL),
(228,'PropertyType.List.FilterBy.DefaultUnits','Filter for property type default units.',NULL),
(229,'PropertyType.List.FilterBy.DefaultValue','Filter for property type default value.',NULL),
(230,'PropertyType.List.FilterBy.Description','Filter for property type description.',NULL),
(231,'PropertyType.List.FilterBy.Handler','Filter for property type class handler.',NULL),
(232,'PropertyType.List.FilterBy.Name','Filter for property type name.',NULL),
(233,'PropertyTypeCategory.List.Display.Description','Display property type category description.','true'),
(234,'PropertyTypeCategory.List.Display.Id','Display property type category id.','false'),
(235,'PropertyTypeCategory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(236,'PropertyTypeCategory.List.FilterBy.Description','Filter for property type category description.',NULL),
(237,'PropertyTypeCategory.List.FilterBy.Name','Filter for property type category name.',NULL),
(238,'PropertyTypeHandler.List.Display.Description','Display property type handler description.','true'),
(239,'PropertyTypeHandler.List.Display.Id','Display property type handler id.','false'),
(240,'PropertyTypeHandler.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(241,'PropertyTypeHandler.List.FilterBy.Description','Filter for property type handler description.',NULL),
(242,'PropertyTypeHandler.List.FilterBy.Name','Filter for property type handler name.',NULL),
(243,'PropertyValue.List.Display.Description','Display value entry description.','false'),
(244,'PropertyValue.List.Display.EnteredOnDateTime','Display value entry entered on date/time.','false'),
(245,'PropertyValue.List.Display.EnteredByUser','Display value entry entered by user.','false'),
(246,'PropertyValue.List.Display.Id','Display property value entry id.','false'),
(247,'PropertyValue.List.Display.IsDynamic','Display dynamic property type designation.','true'),
(248,'PropertyValue.List.Display.IsUserWriteable','Display user-writeable property type designation.','false'),
(249,'PropertyValue.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(250,'PropertyValue.List.Display.Tag','Display property value tag.','true'),
(251,'PropertyValue.List.Display.TypeCategory','Display property value type category.','false'),
(252,'PropertyValue.List.Display.Units','Display value units.','true'),
(253,'PropertyValue.List.FilterBy.Description','Filter for value description.',NULL),
(254,'PropertyValue.List.FilterBy.EnteredOnDateTime','Filter for value entry entered on date/time.',NULL),
(255,'PropertyValue.List.FilterBy.EnteredByUser','Filter for value entry entered by user.',NULL),
(256,'PropertyValue.List.FilterBy.IsDynamic','Filter for dynamic property value designation.',NULL),
(257,'PropertyValue.List.FilterBy.IsUserWriteable','Filter for user-writeable property value designation.',NULL),
(258,'PropertyValue.List.FilterBy.Tag','Filter for property value tag.',NULL),
(259,'PropertyValue.List.FilterBy.Type','Filter for property value type.',NULL),
(260,'PropertyValue.List.FilterBy.TypeCategory','Filter for property value type category.',NULL),
(261,'PropertyValue.List.FilterBy.Units','Filter for value units.',NULL),
(262,'PropertyValue.List.FilterBy.Value','Filter for value entry.',NULL),
(263,'PropertyValueHistory.List.Display.Description','Display value entry description.','true'),
(264,'PropertyValueHistory.List.Display.EnteredOnDateTime','Display value entry entered on date/time.','true'),
(265,'PropertyValueHistory.List.Display.EnteredByUser','Display value entry entered by user.','true'),
(266,'PropertyValueHistory.List.Display.Id','Display property value entry id.','false'),
(267,'PropertyValueHistory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(268,'PropertyValueHistory.List.Display.Tag','Display value tag.','true'),
(269,'PropertyValueHistory.List.Display.Units','Display value units.','true'),
(270,'PropertyValueHistory.List.FilterBy.Description','Filter for value description.',NULL),
(271,'PropertyValueHistory.List.FilterBy.EnteredOnDateTime','Filter for value entry entered on date/time.',NULL),
(272,'PropertyValueHistory.List.FilterBy.EnteredByUser','Filter for value entry entered by user.',NULL),
(273,'PropertyValueHistory.List.FilterBy.Tag','Filter for value tag.',NULL),
(274,'PropertyValueHistory.List.FilterBy.Units','Filter for value units.',NULL),
(275,'PropertyValueHistory.List.FilterBy.Value','Filter for value entry.',NULL),
(276,'Search.CaseInsensitive','Case insensitive search.','true'),
(277,'Search.Display.AssemblyComponents','Display search result for assembly components.','true'),
(278,'Search.Display.Components','Display search result for components.','true'),
(279,'Search.Display.ComponentInstances','Display search result for component instances.','true'),
(280,'Search.Display.ComponentTypes','Display search result for component types.','true'),
(281,'Search.Display.ComponentTypeCategories','Display search result for component type categories.','true'),
(282,'Search.Display.Designs','Display search result for designs.','true'),
(283,'Search.Display.DesignElements','Display search result for design elements.','true'),
(284,'Search.Display.Locations','Display search result for locations.','true'),
(285,'Search.Display.LocationTypes','Display search result for location types.','true'),
(286,'Search.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(287,'Search.Display.PropertyTypes','Display search result for property types.','true'),
(288,'Search.Display.PropertyTypeCategories','Display search result for property type categories.','true'),
(289,'Search.Display.Sources','Display search result for sources.','true'),
(290,'Search.Display.Users','Display search result for users.','true'),
(291,'Search.Display.UserGroups','Display search result for user groups.','true'),
(292,'Source.List.Display.ContactInfo','Display source contact info.','true'),
(293,'Source.List.Display.Description','Display source description.','true'),
(294,'Source.List.Display.Url','Display source URL.','true'),
(295,'Source.List.Display.Id','Display source id.','false'),
(296,'Source.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(297,'Source.List.FilterBy.ContactInfo','Filter for source contact info.',NULL),
(298,'Source.List.FilterBy.Description','Filter for source description.',NULL),
(299,'Source.List.FilterBy.Name','Filter for source name.',NULL),
(300,'Source.List.FilterBy.Url','Filter for source URL.',NULL),
(301,'UserInfo.List.Display.Description','Display user description.','false'),
(302,'UserInfo.List.Display.Email','Display user email.','true'),
(303,'UserInfo.List.Display.FirstName','Display user first name.','true'),
(304,'UserInfo.List.Display.Id','Display user id.','false'),
(305,'UserInfo.List.Display.Groups','Display user groups.','true'),
(306,'UserInfo.List.Display.LastName','Display user last name.','true'),
(307,'UserInfo.List.Display.MiddleName','Display user middle name.','false'),
(308,'UserInfo.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(309,'UserInfo.List.FilterBy.Description','Filter for user description.',NULL),
(310,'UserInfo.List.FilterBy.Email','Filter for user email.',NULL),
(311,'UserInfo.List.FilterBy.FirstName','Filter for user first name.',NULL),
(312,'UserInfo.List.FilterBy.Groups','Filter for user groups.',NULL),
(313,'UserInfo.List.FilterBy.LastName','Filter for user last name.',NULL),
(314,'UserInfo.List.FilterBy.MiddleName','Filter for user middle name.',NULL),
(315,'UserInfo.List.FilterBy.Username','Filter for username.',NULL),
(316,'UserGroup.List.Display.Description','Display user group description.','true'),
(317,'UserGroup.List.Display.Id','Display user group id.','false'),
(318,'UserGroup.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(319,'UserGroup.List.FilterBy.Description','Filter for user group description.',NULL),
(320,'UserGroup.List.FilterBy.Name','Filter for user group name.',NULL),
(321,'UserSetting.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25');
/*!40000 ALTER TABLE `setting_type` ENABLE KEYS */;
UNLOCK TABLES;
