/*
 * Copyright (c) UChicago Argonne, LLC. All rights reserved.
 * See LICENSE file.
 */
package gov.anl.aps.cdb.portal.controllers.extensions;

import gov.anl.aps.cdb.portal.controllers.ItemDomainCableDesignWizardBase;
import gov.anl.aps.cdb.portal.utilities.SessionUtility;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 * Controller for adding cable bundles.
 *
 * @author cmcchesney
 */
@Named(BundleWizard.CONTROLLER_NAMED)
@SessionScoped
public class BundleWizard extends ItemDomainCableDesignWizardBase implements Serializable {

    public static final String CONTROLLER_NAMED = "bundleWizard";
    
    private boolean addMembers = false;
    private boolean createSpares = false;
    
    public static BundleWizard getInstance() {
        return (BundleWizard) SessionUtility.findBean(BundleWizard.CONTROLLER_NAMED);
    } 

    public boolean isAddMembers() {
        return addMembers;
    }

    public void setAddMembers(boolean addMembers) {
        this.addMembers = addMembers;
    }

    public boolean isCreateSpares() {
        return createSpares;
    }

    public void setCreateSpares(boolean createSpares) {
        this.createSpares = createSpares;
    }

    /**
     * Handles select events generated by the "add existing cables" checkbox. 
     */
    public void selectListenerAddMembers() {
        setEnablementForCurrentTab();
    }

    /**
     * Handles select events generated by the "add spares" checkbox. 
     */
    public void selectListenerCreateSpares() {
        setEnablementForCurrentTab();
    }

    /**
     * Implements the save operation, invoked by the wizard's "Save" navigation
     * button.
     */
    public String save() {

        SessionUtility.addErrorMessage(
                "Could not save cable bundle",
                "Feature not yet implemented.");
        return "";
    }
    
    /**
     * Sets enable/disable state for the navigation buttons based on the current
     * tab and input elements.
     */
    @Override
    protected void setEnablement_(String tab) {
        
        if (tab.endsWith("BundleOptionsTab")) {
            disableButtonPrev = false;
            disableButtonCancel = false;
            disableButtonSave = true;
            if (addMembers || createSpares) {
                disableButtonNext = false;
            } else {
                disableButtonNext = true;
            }
        }
    }

}
