LOCK TABLES `component_type` WRITE;
/*!40000 ALTER TABLE `component_type` DISABLE KEYS */;
INSERT INTO `component_type` VALUES
(1,'Girder',NULL,1),
(2,'Cam Movers',NULL,1),
(3,'Pedestals',NULL,1),
(4,'Hardware',NULL,1),
(5,'Magnets',NULL,2),
(6,'Magnet Poles',NULL,2),
(7,'Magnet Pole Mounts',NULL,2),
(8,'Strongbacks / Base Plate',NULL,2),
(9,'Spring Cages',NULL,2),
(10,'Springs',NULL,2),
(11,'Misc.',NULL,2),
(13,'VME Crate',NULL,3),
(14,'UCMI',NULL,3),
(15,'UMPI',NULL,3),
(16,'AC Power Distribution Module',NULL,3),
(17,'Rack',NULL,3),
(18,'Cabling',NULL,3),
(19,'EIC',NULL,3),
(21,'Motors',NULL,3),
(22,'Encoders',NULL,3),
(23,'Limit Switches',NULL,3),
(24,'Quadrupole Magnet',NULL,4),
(25,'Quadrupole Power Supply',NULL,4),
(27,'BPM',NULL,5),
(28,'Beam Loss Monitor',NULL,5),
(30,'Phase Shifter',NULL,6),
(32,'Collimator',NULL,7),
(34,'Vacuum Chamber',NULL,8),
(35,'Bellows/Spool pieces',NULL,8),
(36,'Pump',NULL,8),
(37,'Gauges',NULL,8),
(38,'TBD','To Be Determined later',NULL);
/*!40000 ALTER TABLE `component_type` ENABLE KEYS */;
UNLOCK TABLES;
