TOP=../../..

all install: dist

clean clean-all clean-install distclean: pyc-clean

.PHONY: pyc-clean
pyc-clean:
	rm -f `find . -name '*.pyc'`

# For compiling from command line, we have to use generic build properties file
.PHONY: dist
dist: 


