LOCK TABLES `user_info` WRITE;
/*!40000 ALTER TABLE `user_info` DISABLE KEYS */;
INSERT INTO `user_info` VALUES
(1,'cdb','CDB','System Account',NULL,'cdb@aps.anl.gov',NULL,NULL),
(2,'bstill','Ben','Stillwell','','bstill@aps.anl.gov',NULL,NULL),
(3,'nda','Ned','Arnold','','nda@aps.anl.gov',NULL,NULL),
(4,'sveseli','Sinisa','Veseli','','sveseli@aps.anl.gov',NULL,NULL),
(5,'benes','Scott','Benes','','benes@aps.anl.gov',NULL,NULL),
(6,'nschwarz','Nicholas','Schwarz','','nschwarz@aps.anl.gov',NULL,NULL),
(7,'cease','Herman','Cease','','cease@aps.anl.gov',NULL,NULL),
(8,'carwar','John','Carwardine','','carwar@aps.anl.gov',NULL,''),
(9,'decker','Glenn','Decker','','decker@aps.anl.gov',NULL,NULL),
(10,'ngrossman','Nancy','Grossman','','ngrossman@aps.anl.gov',NULL,NULL),
(11,'cprokuski','Chuck','Prokuski','','cprokuski@aps.anl.gov',NULL,NULL),
(12,'jaski','Mark','Jaski','','jaski@aps.anl.gov',NULL,NULL),
(13,'juw','Ju','Wang','','juw@aps.anl.gov',NULL,NULL),
(14,'blill','Bob','Lill','','blill@aps.anl.gov',NULL,NULL),
(15,'horan','Doug','Horan','','horan@aps.anl.gov',NULL,NULL),
(16,'fornek','Tom','Fornek','','fornek@aps.anl.gov',NULL,NULL),
(17,'rif','Richard','Farnsworth','','rif@aps.anl.gov',NULL,NULL),
(18,'frl','Frank','Lenkszus','','frl@aps.anl.gov',NULL,NULL),
(19,'preissner','Curt','Preissner','','preissner@aps.anl.gov',NULL,NULL),
(20,'lhm','Leonard','Morrison','','lhm@aps.anl.gov',NULL,NULL),
(21,'jieliu','Jie','Liu','','jieliu@aps.anl.gov',NULL,NULL),
(22,'doose','Charles','Doose','','doose@aps.anl.gov',NULL,NULL),
(23,'tfors','Tom','Fors','','tfors@aps.anl.gov',NULL,''),
(24,'bran','Bran','Brajuskovic','','bran@aps.anl.gov',NULL,NULL),
(25,'jzientek','John','Zientek','','jzientek@aps.anl.gov',NULL,NULL),
(26,'djarosz','Dariusz','Jarosz','Piotr','djarosz@aps.anl.gov',NULL,NULL),
(27,'mwhite','Marion','White','','mwhite@aps.anl.gov',NULL,NULL),
(28,'brianr','Brian','Rusthoven','','brianr@aps.anl.gov',NULL,NULL),
(29,'shoaf','Steve','Shoaf','','shoaf@aps.anl.gov',NULL,NULL),
(30,'hbui','Hanh','Bui','','hbui@aps.anl.gov',NULL,NULL),
(31,'sereno','Nick','Sereno','','sereno@aps.anl.ogv',NULL,NULL),
(32,'xusf','Shifu','Xu','','xusf@aps.anl.gov',NULL,NULL),
(33,'afp','Tony','Pietryla','','afp',NULL,NULL),
(34,'rblake','Ron','Blake','','rblake@aps.anl.gov',NULL,NULL),
(35,'dejus','Roger','Dejus','','dejus@aps.anl.gov',NULL,NULL),
(36,'collins','Jeff','Collins','','collins@aps.anl.gov',NULL,NULL),
(37,'keane','Rob','Keane','','keane@aps.anl.gov',NULL,NULL),
(38,'jzxu','Joe','Xu','','jzxu@aps.anl.gov',NULL,NULL),
(39,'jnudell','Jeremy','Nudell','','jnudell@aps.anl.gov',NULL,NULL),
(40,'borland','Michael','Borland','','borland@aps.anl.gov',NULL,NULL),
(41,'soprondek','Samuel','Oprondek','','soprondek@aps.anl.gov','ziZy$VHwn+tdgAX6uwMZf1mA2c0By8DdnuCbp',NULL),
(42,'jtoeller','Jeff','Toeller','','jtoeller@aps.anl.gov',NULL,''),
(43,'berenc','Tim','Berenc','','berenc@aps.anl.gov','RDY0$mLyUX9cWeaPgq0iTqma3hyIW8WWNHCc5',''),
(44,'jox','Julie','Cross','Olmted','jox@anl.gov',NULL,''),
(45,'jabraham','Josh','Abraham','','jabraham@anl.gov',NULL,'');
/*!40000 ALTER TABLE `user_info` ENABLE KEYS */;
UNLOCK TABLES;
