# coding: utf-8

"""
    Component Database API

    The API that provides access to Component Database data.  # noqa: E501

    The version of the OpenAPI document: 3.12.3
    Contact: djarosz@anl.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cdbApi.configuration import Configuration


class FileUploadObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_name': 'str',
        'base64_binary': 'str'
    }

    attribute_map = {
        'file_name': 'fileName',
        'base64_binary': 'base64Binary'
    }

    def __init__(self, file_name=None, base64_binary=None, local_vars_configuration=None):  # noqa: E501
        """FileUploadObject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file_name = None
        self._base64_binary = None
        self.discriminator = None

        if file_name is not None:
            self.file_name = file_name
        if base64_binary is not None:
            self.base64_binary = base64_binary

    @property
    def file_name(self):
        """Gets the file_name of this FileUploadObject.  # noqa: E501


        :return: The file_name of this FileUploadObject.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this FileUploadObject.


        :param file_name: The file_name of this FileUploadObject.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def base64_binary(self):
        """Gets the base64_binary of this FileUploadObject.  # noqa: E501


        :return: The base64_binary of this FileUploadObject.  # noqa: E501
        :rtype: str
        """
        return self._base64_binary

    @base64_binary.setter
    def base64_binary(self, base64_binary):
        """Sets the base64_binary of this FileUploadObject.


        :param base64_binary: The base64_binary of this FileUploadObject.  # noqa: E501
        :type: str
        """

        self._base64_binary = base64_binary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileUploadObject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FileUploadObject):
            return True

        return self.to_dict() != other.to_dict()
