# coding: utf-8

"""
    Component Database API

    The API that provides access to Component Database data.  # noqa: E501

    The version of the OpenAPI document: 3.12.3
    Contact: djarosz@anl.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cdbApi.configuration import Configuration


class UserRole(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'role_type': 'RoleType',
        'user_group': 'UserGroup'
    }

    attribute_map = {
        'role_type': 'roleType',
        'user_group': 'userGroup'
    }

    def __init__(self, role_type=None, user_group=None, local_vars_configuration=None):  # noqa: E501
        """UserRole - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._role_type = None
        self._user_group = None
        self.discriminator = None

        if role_type is not None:
            self.role_type = role_type
        if user_group is not None:
            self.user_group = user_group

    @property
    def role_type(self):
        """Gets the role_type of this UserRole.  # noqa: E501


        :return: The role_type of this UserRole.  # noqa: E501
        :rtype: RoleType
        """
        return self._role_type

    @role_type.setter
    def role_type(self, role_type):
        """Sets the role_type of this UserRole.


        :param role_type: The role_type of this UserRole.  # noqa: E501
        :type: RoleType
        """

        self._role_type = role_type

    @property
    def user_group(self):
        """Gets the user_group of this UserRole.  # noqa: E501


        :return: The user_group of this UserRole.  # noqa: E501
        :rtype: UserGroup
        """
        return self._user_group

    @user_group.setter
    def user_group(self, user_group):
        """Sets the user_group of this UserRole.


        :param user_group: The user_group of this UserRole.  # noqa: E501
        :type: UserGroup
        """

        self._user_group = user_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserRole):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserRole):
            return True

        return self.to_dict() != other.to_dict()
